import express, { type NextFunction, type Request, type Response } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { resolve } from 'node:path';
import { existsSync } from 'node:fs';
import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import { env } from './config.js';
import { db, initializeDatabase, rows, transaction } from './db.js';
import { authenticate, type AuthRequest } from './middleware/auth.js';
import { abortRun, getDataset, getRun, startActor } from './services/apify.js';
import { engagement, normalizePost, normalizeUsername } from './services/normalizer.js';
import {decryptSecret,encryptSecret,generateProfileAnalysis,testAiConnection,type AiProvider} from './services/ai.js';
import {sendSmtpTest,type SmtpConfiguration} from './services/email.js';

const app = express();
app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: env.NODE_ENV === 'production' ? { directives: {
  defaultSrc:["'self'"],baseUri:["'self'"],fontSrc:["'self'",'https:','data:'],formAction:["'self'"],frameAncestors:["'self'"],
  imgSrc:["'self'",'data:','https://*.cdninstagram.com','https://*.fbcdn.net'],mediaSrc:["'self'",'blob:','https://*.cdninstagram.com','https://*.fbcdn.net'],
  objectSrc:["'none'"],scriptSrc:["'self'"],scriptSrcAttr:["'none'"],styleSrc:["'self'",'https:',"'unsafe-inline'"],upgradeInsecureRequests:[]
} } : false }));
app.use(cors({ origin: env.FRONTEND_URL.split(',').map(x => x.trim()), credentials: true }));
app.use(express.json({ limit: '2mb' }));
app.use('/api', rateLimit({ windowMs: 60_000, limit: 180, standardHeaders: true, legacyHeaders: false }));

const wrap = (handler: (req: AuthRequest, res: Response) => Promise<unknown>) => (req: AuthRequest, res: Response, next: NextFunction) => Promise.resolve(handler(req, res)).catch(next);
const idOf = (req: Request) => z.coerce.number().int().positive().parse(req.params.id);
const profileSchema = z.object({ username: z.string().min(1).max(300), internalName: z.string().max(120).optional().nullable(), isActive: z.boolean().optional() });
const collectSchema = z.object({ type: z.enum(['profile_details','posts','stories','comments','full']).default('full'), limit: z.number().int().min(1).max(500).default(100), newerThan: z.string().max(50).default('30 days') });
const collectionPeriodSchema=z.string().trim().min(3).max(50).refine(value=>/^\d+\s+(minutes?|hours?|days?|weeks?|months?|years?)$/i.test(value)||/^\d{4}-\d{2}-\d{2}(?:T.*)?$/.test(value),{message:'Use um período como 45 days, 6 months ou uma data como 2026-01-01.'});
const collectionSettingsSchema=z.object({resultsLimit:z.number().int().min(1).max(500),onlyPostsNewerThan:collectionPeriodSchema,postsUntil:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional()}).superRefine((value,context)=>{if(value.postsUntil){if(!/^\d{4}-\d{2}-\d{2}$/.test(value.onlyPostsNewerThan))context.addIssue({code:'custom',path:['onlyPostsNewerThan'],message:'Para usar data final, informe uma data inicial.'});else if(value.postsUntil<value.onlyPostsNewerThan)context.addIssue({code:'custom',path:['postsUntil'],message:'A data final deve ser igual ou posterior à inicial.'});}});
type CollectionInput=z.infer<typeof collectSchema>&{olderThan:string|null};
const screenKeys=['dashboard','profiles','comparisons','comparison_groups','collections','settings','system_users','access_profiles'] as const;
const screenKeySchema=z.enum(screenKeys);
const accessProfileSchema=z.object({name:z.string().trim().min(2).max(120),description:z.string().trim().max(500).optional().nullable(),isActive:z.boolean().default(true),permissions:z.array(screenKeySchema).default([])});
const userSchema=z.object({name:z.string().trim().min(2).max(120),email:z.string().email().max(190),password:z.string().min(8).max(200).optional(),role:z.enum(['admin','user']).default('user'),accessProfileId:z.number().int().positive().nullable().optional(),isActive:z.boolean().default(true)}).superRefine((value,context)=>{if(value.role==='user'&&!value.accessProfileId)context.addIssue({code:'custom',path:['accessProfileId'],message:'Selecione um perfil de acesso para o usuário.'});});

app.get('/api/health', wrap(async (_req, res) => {
  await db.query('SELECT 1'); res.json({ status: 'ok', database: 'connected', timestamp: new Date().toISOString() });
}));
app.post('/api/auth/login', rateLimit({ windowMs: 15 * 60_000, limit: 10 }), wrap(async (req, res) => {
  const input = z.object({ email: z.string().email(), password: z.string().min(1) }).parse(req.body);
  const users = await rows<(RowDataPacket & { id:number; name:string; email:string; role:string; password_hash:string; access_profile_id:number|null; access_profile_name:string|null; permissions:string|null })[]>(`SELECT u.*,ap.name access_profile_name,GROUP_CONCAT(app.screen_key) permissions FROM users u LEFT JOIN access_profiles ap ON ap.id=u.access_profile_id AND ap.is_active=1 LEFT JOIN access_profile_permissions app ON app.access_profile_id=ap.id WHERE u.email=? AND u.is_active=1 GROUP BY u.id LIMIT 1`, [input.email.toLowerCase()]);
  const user = users[0];
  if (!user || !(await bcrypt.compare(input.password, user.password_hash))) return res.status(401).json({ message: 'E-mail ou senha incorretos.' });
  const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, env.JWT_SECRET, { expiresIn: env.JWT_EXPIRES_IN as jwt.SignOptions['expiresIn'] });
  res.json({ token, user: { id:user.id, name:user.name, email:user.email, role:user.role,accessProfileId:user.access_profile_id?Number(user.access_profile_id):null,accessProfileName:user.access_profile_name,permissions:user.role==='admin'?[...screenKeys]:String(user.permissions||'').split(',').filter(Boolean) } });
}));
app.get('/api/auth/me', authenticate, wrap(async (req, res) => {
  const users = await rows<RowDataPacket[]>('SELECT u.id,u.name,u.email,u.role,u.access_profile_id accessProfileId,ap.name accessProfileName FROM users u LEFT JOIN access_profiles ap ON ap.id=u.access_profile_id WHERE u.id=? AND u.is_active=1', [req.user!.id]); res.json({...users[0],permissions:req.user!.role==='admin'?[...screenKeys]:req.user!.permissions});
}));
app.post('/api/auth/logout', authenticate, (_req, res) => res.status(204).end());
app.get('/api/media/profiles/:id/picture',wrap(async(req,res)=>{const profiles=await rows<(RowDataPacket&{profile_picture_url:string|null})[]>('SELECT profile_picture_url FROM instagram_profiles WHERE id=?',[idOf(req)]);const picture=profiles[0]?.profile_picture_url;if(!picture)return res.status(404).end();const url=new URL(picture);if(url.protocol!=='https:'||(!url.hostname.endsWith('.cdninstagram.com')&&!url.hostname.endsWith('.fbcdn.net')))return res.status(400).end();const response=await fetch(url,{headers:{'user-agent':'Mozilla/5.0'}});if(!response.ok)return res.status(404).end();const contentType=response.headers.get('content-type')||'image/jpeg';if(!contentType.startsWith('image/'))return res.status(415).end();res.set({'Content-Type':contentType,'Cache-Control':'public, max-age=3600, stale-while-revalidate=86400'});res.send(Buffer.from(await response.arrayBuffer()));}));

app.use('/api', authenticate);
const permissionsForRequest=(req:AuthRequest):string[]=>{const path=req.path;if(path==='/access-profiles'&&req.method==='GET')return['access_profiles','system_users'];if(path.startsWith('/access-profiles'))return['access_profiles'];if(path.startsWith('/system-users'))return['system_users'];if(/^\/profiles\/\d+\/set-base$/.test(path))return['dashboard'];if(/^\/profiles\/\d+\/collect$/.test(path))return['profiles'];if(path==='/profiles'&&req.method==='GET')return['profiles','comparison_groups','collections','comparisons'];if(path.startsWith('/comparison-groups'))return['comparison_groups'];if(path.startsWith('/comparisons'))return['comparisons'];if(path.startsWith('/collection-settings')||path.startsWith('/email/settings'))return['settings'];if(path.startsWith('/collections')||path.startsWith('/runs'))return['collections'];if(path.startsWith('/ai/settings'))return['settings'];if(path.startsWith('/ai/analysis')||path.startsWith('/ai/analyze')||path.startsWith('/dashboard'))return['dashboard'];if(path.startsWith('/posts')||path.startsWith('/profiles'))return['profiles'];return[];};
app.use('/api',(req:AuthRequest,res,next)=>{if(req.user?.role==='admin')return next();const permissions=permissionsForRequest(req);if(!permissions.length||permissions.some(permission=>req.user?.permissions.includes(permission)))return next();return res.status(403).json({message:'Seu perfil de acesso não permite abrir esta área.'});});
const requireManagement=(...permissions:Array<'system_users'|'access_profiles'>)=>(req:AuthRequest,res:Response,next:NextFunction)=>req.user?.role==='admin'||permissions.some(permission=>req.user?.permissions.includes(permission))?next():res.status(403).json({message:'Seu perfil não permite gerenciar esta área.'});
async function validateUserAccessProfile(role:'admin'|'user',accessProfileId:number|null|undefined){if(role==='admin')return;const found=await rows<RowDataPacket[]>('SELECT id FROM access_profiles WHERE id=? AND is_active=1',[accessProfileId]);if(!found[0])throw Object.assign(new Error('Selecione um perfil de acesso ativo.'),{status:400});}

app.get('/api/access-profiles',requireManagement('access_profiles','system_users'),wrap(async(_req,res)=>{const profiles=await rows<RowDataPacket[]>(`SELECT ap.*,COUNT(DISTINCT u.id) user_count,COALESCE(GROUP_CONCAT(DISTINCT app.screen_key ORDER BY app.screen_key SEPARATOR ','),'') permissions FROM access_profiles ap LEFT JOIN users u ON u.access_profile_id=ap.id LEFT JOIN access_profile_permissions app ON app.access_profile_id=ap.id GROUP BY ap.id ORDER BY ap.name`);res.json(profiles.map((profile:any)=>({...profile,is_active:Boolean(profile.is_active),permissions:String(profile.permissions||'').split(',').filter(Boolean),user_count:Number(profile.user_count)})));}));
app.post('/api/access-profiles',requireManagement('access_profiles'),wrap(async(req,res)=>{const input=accessProfileSchema.parse(req.body);const id=await transaction(async connection=>{const [created]=await connection.execute<ResultSetHeader>('INSERT INTO access_profiles(name,description,is_active,created_by) VALUES(?,?,?,?)',[input.name,input.description||null,input.isActive,req.user!.id]);for(const permission of [...new Set(input.permissions)])await connection.execute('INSERT INTO access_profile_permissions(access_profile_id,screen_key) VALUES(?,?)',[created.insertId,permission]);return Number(created.insertId)});res.status(201).json({id});}));
app.put('/api/access-profiles/:id',requireManagement('access_profiles'),wrap(async(req,res)=>{const profileId=idOf(req);const input=accessProfileSchema.parse(req.body);await transaction(async connection=>{const [updated]=await connection.execute<ResultSetHeader>('UPDATE access_profiles SET name=?,description=?,is_active=? WHERE id=?',[input.name,input.description||null,input.isActive,profileId]);if(!updated.affectedRows)throw Object.assign(new Error('Perfil de acesso não encontrado.'),{status:404});await connection.execute('DELETE FROM access_profile_permissions WHERE access_profile_id=?',[profileId]);for(const permission of [...new Set(input.permissions)])await connection.execute('INSERT INTO access_profile_permissions(access_profile_id,screen_key) VALUES(?,?)',[profileId,permission]);});res.status(204).end();}));
app.delete('/api/access-profiles/:id',requireManagement('access_profiles'),wrap(async(req,res)=>{const profileId=idOf(req);const assigned=await rows<(RowDataPacket&{total:number})[]>('SELECT COUNT(*) total FROM users WHERE access_profile_id=?',[profileId]);if(Number(assigned[0]?.total))return res.status(409).json({message:'Remova ou altere os usuários associados antes de excluir este perfil.'});await db.execute('DELETE FROM access_profiles WHERE id=?',[profileId]);res.status(204).end();}));

app.get('/api/system-users',requireManagement('system_users'),wrap(async(req,res)=>{const where=req.user!.role==='admin'?'':`WHERE u.role='user'`;res.json(await rows<RowDataPacket[]>(`SELECT u.id,u.name,u.email,u.role,u.is_active,u.access_profile_id,ap.name access_profile_name,u.created_at,u.updated_at FROM users u LEFT JOIN access_profiles ap ON ap.id=u.access_profile_id ${where} ORDER BY u.name`));}));
app.post('/api/system-users',requireManagement('system_users'),wrap(async(req,res)=>{const input=userSchema.safeExtend({password:z.string().min(8,'A senha deve ter pelo menos 8 caracteres.').max(200)}).parse(req.body);if(req.user!.role!=='admin'&&input.role==='admin')return res.status(403).json({message:'Somente administradores podem criar outras contas administrativas.'});await validateUserAccessProfile(input.role,input.accessProfileId);const passwordHash=await bcrypt.hash(input.password,12);const values:any[]=[input.name,input.email.toLowerCase(),passwordHash,input.role,input.role==='admin'?null:input.accessProfileId,input.isActive];try{const [created]=await db.execute<ResultSetHeader>('INSERT INTO users(name,email,password_hash,role,access_profile_id,is_active) VALUES(?,?,?,?,?,?)',values);res.status(201).json({id:Number(created.insertId)});}catch(error:any){if(error.code==='ER_DUP_ENTRY')return res.status(409).json({message:'Já existe um usuário com este e-mail.'});if(error.code==='ER_NO_REFERENCED_ROW_2')return res.status(400).json({message:'O perfil de acesso selecionado não está mais disponível.'});throw error;}}));
app.put('/api/system-users/:id',requireManagement('system_users'),wrap(async(req,res)=>{const userId=idOf(req);const input=userSchema.parse(req.body);const target=await rows<(RowDataPacket&{role:string})[]>('SELECT role FROM users WHERE id=?',[userId]);if(!target[0])return res.status(404).json({message:'Usuário não encontrado.'});if(req.user!.role!=='admin'&&(userId===req.user!.id||target[0].role==='admin'||input.role==='admin'))return res.status(403).json({message:'Este usuário só pode ser alterado por um administrador.'});if(userId===req.user!.id&&(!input.isActive||input.role!=='admin'))return res.status(400).json({message:'Você não pode desativar ou remover seu próprio acesso administrativo.'});await validateUserAccessProfile(input.role,input.accessProfileId);const fields=['name=?','email=?','role=?','access_profile_id=?','is_active=?'];const values:any[]=[input.name,input.email.toLowerCase(),input.role,input.role==='admin'?null:input.accessProfileId,input.isActive];if(input.password){fields.push('password_hash=?');values.push(await bcrypt.hash(input.password,12))}values.push(userId);try{await db.execute(`UPDATE users SET ${fields.join(',')} WHERE id=?`,values);res.status(204).end();}catch(error:any){if(error.code==='ER_DUP_ENTRY')return res.status(409).json({message:'Já existe um usuário com este e-mail.'});throw error;}}));
app.delete('/api/system-users/:id',requireManagement('system_users'),wrap(async(req,res)=>{const userId=idOf(req);if(userId===req.user!.id)return res.status(400).json({message:'Você não pode excluir seu próprio usuário.'});const target=await rows<(RowDataPacket&{role:string})[]>('SELECT role FROM users WHERE id=?',[userId]);if(!target[0])return res.status(404).json({message:'Usuário não encontrado.'});if(req.user!.role!=='admin'&&target[0].role==='admin')return res.status(403).json({message:'Somente administradores podem excluir outra conta administrativa.'});await db.execute('DELETE FROM users WHERE id=?',[userId]);res.status(204).end();}));
const aiSettingsSchema=z.object({enabled:z.boolean(),provider:z.enum(['openai','anthropic']),openaiModel:z.string().trim().min(2).max(100),anthropicModel:z.string().trim().min(2).max(100),openaiApiKey:z.string().trim().max(500).optional(),anthropicApiKey:z.string().trim().max(500).optional()});
type AiSettingsRow=RowDataPacket&{ai_enabled:number;ai_provider:AiProvider;openai_model:string;anthropic_model:string;openai_api_key_encrypted:string|null;anthropic_api_key_encrypted:string|null;ai_last_tested_at:Date|null;base_profile_id:number|null};
async function getAiSettingsRow(){const found=await rows<AiSettingsRow[]>('SELECT base_profile_id,ai_enabled,ai_provider,openai_model,anthropic_model,openai_api_key_encrypted,anthropic_api_key_encrypted,ai_last_tested_at FROM workspace_settings WHERE id=1');return found[0]||{ai_enabled:0,ai_provider:'openai',openai_model:'gpt-5.6-sol',anthropic_model:'claude-sonnet-4-6',openai_api_key_encrypted:null,anthropic_api_key_encrypted:null,ai_last_tested_at:null,base_profile_id:null} as AiSettingsRow}
function publicAiSettings(setting:AiSettingsRow){return{enabled:Boolean(setting.ai_enabled),provider:setting.ai_provider,openaiModel:setting.openai_model||'gpt-5.6-sol',anthropicModel:setting.anthropic_model||'claude-sonnet-4-6',openaiConfigured:Boolean(setting.openai_api_key_encrypted),anthropicConfigured:Boolean(setting.anthropic_api_key_encrypted),lastTestedAt:setting.ai_last_tested_at}}
function configuredAi(setting:AiSettingsRow,provider:AiProvider){const encrypted=provider==='openai'?setting.openai_api_key_encrypted:setting.anthropic_api_key_encrypted;if(!encrypted)throw Object.assign(new Error(`Configure a chave da ${provider==='openai'?'OpenAI':'Anthropic'} antes de continuar.`),{status:400});return{key:decryptSecret(encrypted,env.JWT_SECRET),model:provider==='openai'?setting.openai_model:setting.anthropic_model}}
app.get('/api/ai/settings',wrap(async(_req,res)=>res.json(publicAiSettings(await getAiSettingsRow()))));
app.put('/api/ai/settings',wrap(async(req,res)=>{const input=aiSettingsSchema.parse(req.body);const current=await getAiSettingsRow();const openaiEncrypted=input.openaiApiKey?encryptSecret(input.openaiApiKey,env.JWT_SECRET):current.openai_api_key_encrypted;const anthropicEncrypted=input.anthropicApiKey?encryptSecret(input.anthropicApiKey,env.JWT_SECRET):current.anthropic_api_key_encrypted;if(input.enabled&&!(input.provider==='openai'?openaiEncrypted:anthropicEncrypted))return res.status(400).json({message:'Informe a chave do provedor selecionado para ativar a IA.'});await db.execute(`INSERT INTO workspace_settings(id,ai_enabled,ai_provider,openai_model,anthropic_model,openai_api_key_encrypted,anthropic_api_key_encrypted,updated_by) VALUES(1,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE ai_enabled=VALUES(ai_enabled),ai_provider=VALUES(ai_provider),openai_model=VALUES(openai_model),anthropic_model=VALUES(anthropic_model),openai_api_key_encrypted=VALUES(openai_api_key_encrypted),anthropic_api_key_encrypted=VALUES(anthropic_api_key_encrypted),updated_by=VALUES(updated_by)`,[input.enabled,input.provider,input.openaiModel,input.anthropicModel,openaiEncrypted,anthropicEncrypted,req.user!.id]);res.json(publicAiSettings(await getAiSettingsRow()))}));
app.post('/api/ai/settings/test',rateLimit({windowMs:60_000,limit:5}),wrap(async(req,res)=>{const input=z.object({provider:z.enum(['openai','anthropic']),model:z.string().trim().min(2).max(100),apiKey:z.string().trim().max(500).optional()}).parse(req.body);const setting=await getAiSettingsRow();const key=input.apiKey||configuredAi(setting,input.provider).key;await testAiConnection(input.provider,input.model,key);await db.execute(`INSERT INTO workspace_settings(id,ai_last_tested_at,updated_by) VALUES(1,UTC_TIMESTAMP(),?) ON DUPLICATE KEY UPDATE ai_last_tested_at=UTC_TIMESTAMP(),updated_by=VALUES(updated_by)`,[req.user!.id]);res.json({ok:true,testedAt:new Date().toISOString()})}));

const emailSettingsSchema=z.object({enabled:z.boolean(),host:z.string().trim().max(255),port:z.number().int().min(1).max(65535),secure:z.boolean(),requireTls:z.boolean(),user:z.string().trim().max(255),password:z.string().max(500).optional(),fromName:z.string().trim().max(120),fromAddress:z.string().trim().email().or(z.literal('')),replyTo:z.string().trim().email().or(z.literal('')).optional(),notifyPasswords:z.boolean(),notifyReports:z.boolean(),notifySystem:z.boolean()}).superRefine((value,context)=>{if(!value.enabled)return;if(!value.host)context.addIssue({code:'custom',path:['host'],message:'Informe o servidor SMTP.'});if(!value.fromName)context.addIssue({code:'custom',path:['fromName'],message:'Informe o nome do remetente.'});if(!value.fromAddress)context.addIssue({code:'custom',path:['fromAddress'],message:'Informe o e-mail do remetente.'});});
type EmailSettingsRow=RowDataPacket&{email_enabled:number;smtp_host:string|null;smtp_port:number;smtp_secure:number;smtp_require_tls:number;smtp_user:string|null;smtp_password_encrypted:string|null;email_from_name:string|null;email_from_address:string|null;email_reply_to:string|null;email_notify_passwords:number;email_notify_reports:number;email_notify_system:number;email_last_tested_at:Date|null};
async function getEmailSettingsRow(){const found=await rows<EmailSettingsRow[]>('SELECT email_enabled,smtp_host,smtp_port,smtp_secure,smtp_require_tls,smtp_user,smtp_password_encrypted,email_from_name,email_from_address,email_reply_to,email_notify_passwords,email_notify_reports,email_notify_system,email_last_tested_at FROM workspace_settings WHERE id=1');return found[0]||{email_enabled:0,smtp_host:'',smtp_port:587,smtp_secure:0,smtp_require_tls:1,smtp_user:'',smtp_password_encrypted:null,email_from_name:'Studek Analytics',email_from_address:'',email_reply_to:'',email_notify_passwords:1,email_notify_reports:1,email_notify_system:1,email_last_tested_at:null} as EmailSettingsRow}
function publicEmailSettings(setting:EmailSettingsRow){return{enabled:Boolean(setting.email_enabled),host:setting.smtp_host||'',port:Number(setting.smtp_port||587),secure:Boolean(setting.smtp_secure),requireTls:Boolean(setting.smtp_require_tls),user:setting.smtp_user||'',passwordConfigured:Boolean(setting.smtp_password_encrypted),fromName:setting.email_from_name||'Studek Analytics',fromAddress:setting.email_from_address||'',replyTo:setting.email_reply_to||'',notifyPasswords:Boolean(setting.email_notify_passwords),notifyReports:Boolean(setting.email_notify_reports),notifySystem:Boolean(setting.email_notify_system),lastTestedAt:setting.email_last_tested_at}}
function smtpConfiguration(input:z.infer<typeof emailSettingsSchema>,encryptedPassword:string|null):SmtpConfiguration{if(!input.host||!input.fromAddress||!input.fromName)throw Object.assign(new Error('Preencha o servidor e os dados do remetente.'),{status:400});if(input.user&&!encryptedPassword)throw Object.assign(new Error('Informe a senha SMTP.'),{status:400});return{host:input.host,port:input.port,secure:input.secure,requireTls:input.requireTls,user:input.user,password:encryptedPassword?decryptSecret(encryptedPassword,env.JWT_SECRET):'',fromName:input.fromName,fromAddress:input.fromAddress,replyTo:input.replyTo||null}}
app.get('/api/email/settings',wrap(async(_req,res)=>res.json(publicEmailSettings(await getEmailSettingsRow()))));
app.put('/api/email/settings',wrap(async(req,res)=>{const input=emailSettingsSchema.parse(req.body);const current=await getEmailSettingsRow();const passwordEncrypted=input.password?encryptSecret(input.password,env.JWT_SECRET):current.smtp_password_encrypted;if(input.enabled)smtpConfiguration(input,passwordEncrypted);await db.execute(`INSERT INTO workspace_settings(id,email_enabled,smtp_host,smtp_port,smtp_secure,smtp_require_tls,smtp_user,smtp_password_encrypted,email_from_name,email_from_address,email_reply_to,email_notify_passwords,email_notify_reports,email_notify_system,updated_by) VALUES(1,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE email_enabled=VALUES(email_enabled),smtp_host=VALUES(smtp_host),smtp_port=VALUES(smtp_port),smtp_secure=VALUES(smtp_secure),smtp_require_tls=VALUES(smtp_require_tls),smtp_user=VALUES(smtp_user),smtp_password_encrypted=VALUES(smtp_password_encrypted),email_from_name=VALUES(email_from_name),email_from_address=VALUES(email_from_address),email_reply_to=VALUES(email_reply_to),email_notify_passwords=VALUES(email_notify_passwords),email_notify_reports=VALUES(email_notify_reports),email_notify_system=VALUES(email_notify_system),updated_by=VALUES(updated_by)`,[input.enabled,input.host||null,input.port,input.secure,input.requireTls,input.user||null,passwordEncrypted,input.fromName||null,input.fromAddress||null,input.replyTo||null,input.notifyPasswords,input.notifyReports,input.notifySystem,req.user!.id]);res.json(publicEmailSettings(await getEmailSettingsRow()))}));
app.post('/api/email/settings/test',rateLimit({windowMs:60_000,limit:5}),wrap(async(req,res)=>{const input=emailSettingsSchema.safeExtend({testTo:z.string().trim().email()}).parse(req.body);const current=await getEmailSettingsRow();const passwordEncrypted=input.password?encryptSecret(input.password,env.JWT_SECRET):current.smtp_password_encrypted;try{await sendSmtpTest(smtpConfiguration(input,passwordEncrypted),input.testTo)}catch(error){console.error('Falha no teste SMTP:',error);throw Object.assign(new Error('Não foi possível conectar ou enviar pelo SMTP. Confira servidor, porta, segurança e credenciais.'),{status:502})}await db.execute(`INSERT INTO workspace_settings(id,email_last_tested_at,updated_by) VALUES(1,UTC_TIMESTAMP(),?) ON DUPLICATE KEY UPDATE email_last_tested_at=UTC_TIMESTAMP(),updated_by=VALUES(updated_by)`,[req.user!.id]);res.json({ok:true,testedAt:new Date().toISOString()})}));

async function aiSourceSnapshot(profileId:number){
  const baseRows=await rows<RowDataPacket[]>(`SELECT p.id,p.username,p.full_name,p.internal_name,p.biography,p.category,p.external_url,p.last_collected_at,COALESCE(s.followers_count,0) followers,COALESCE(s.follows_count,0) following,COALESCE(s.posts_count,0) totalPosts,COALESCE(s.average_likes,0) averageLikes,COALESCE(s.average_comments,0) averageComments,COALESCE(s.average_engagement,0) averageEngagement,COALESCE(s.engagement_rate,0) engagementRate,(SELECT followers_count FROM profile_snapshots WHERE profile_id=p.id AND followers_count>0 ORDER BY collected_at LIMIT 1) firstFollowers,(SELECT COUNT(*) FROM instagram_posts ip WHERE ip.profile_id=p.id AND ip.published_at>=UTC_TIMESTAMP()-INTERVAL 30 DAY) posts30Days FROM instagram_profiles p LEFT JOIN profile_snapshots s ON s.id=(SELECT id FROM profile_snapshots WHERE profile_id=p.id ORDER BY collected_at DESC LIMIT 1) WHERE p.id=?`,[profileId]);
  const profile:any=baseRows[0];if(!profile)throw Object.assign(new Error('Perfil base não encontrado.'),{status:404});
  const grouped=await rows<(RowDataPacket&{id:number})[]>(`SELECT DISTINCT gp.profile_id id FROM comparison_group_profiles gp WHERE gp.comparison_group_id IN (SELECT comparison_group_id FROM comparison_group_profiles WHERE profile_id=?) AND gp.profile_id<>?`,[profileId,profileId]);
  const groupedIds=grouped.map(item=>Number(item.id));const competitorFilter=groupedIds.length?`p.id IN (${groupedIds.map(()=>'?').join(',')})`:'p.id<>?';const competitorValues=groupedIds.length?groupedIds:[profileId];
  const competitors=await rows<RowDataPacket[]>(`SELECT p.id,p.username,p.full_name,p.biography,p.category,p.external_url,p.last_collected_at,COALESCE(s.followers_count,0) followers,COALESCE(s.engagement_rate,0) engagementRate,COALESCE(s.average_likes,0) averageLikes,COALESCE(s.average_comments,0) averageComments,COALESCE(s.average_engagement,0) averageEngagement,(SELECT COUNT(*) FROM instagram_posts ip WHERE ip.profile_id=p.id AND ip.published_at>=UTC_TIMESTAMP()-INTERVAL 30 DAY) posts30Days FROM instagram_profiles p LEFT JOIN profile_snapshots s ON s.id=(SELECT id FROM profile_snapshots WHERE profile_id=p.id ORDER BY collected_at DESC LIMIT 1) WHERE p.is_active=1 AND ${competitorFilter} ORDER BY s.engagement_rate DESC LIMIT 7`,competitorValues);
  const analyzedProfiles=[profile,...competitors];const ids=analyzedProfiles.map(item=>Number(item.id));const marks=ids.map(()=>'?').join(',');
  const posts=await rows<RowDataPacket[]>(`SELECT ranked.* FROM (SELECT p.id,p.profile_id,p.post_type,p.content_surface,LEFT(COALESCE(p.caption,''),300) caption,p.published_at,COALESCE(m.likes_count,0) likes,COALESCE(m.comments_count,0) comments,COALESCE(m.views_count,0) views,COALESCE(m.plays_count,0) plays,COALESCE(m.engagement_count,0) engagement,COALESCE((SELECT GROUP_CONCAT(h.name ORDER BY h.name SEPARATOR ',') FROM post_hashtags ph JOIN hashtags h ON h.id=ph.hashtag_id WHERE ph.post_id=p.id),'') hashtags,ROW_NUMBER() OVER(PARTITION BY p.profile_id ORDER BY COALESCE(m.engagement_count,0) DESC) profile_rank FROM instagram_posts p LEFT JOIN post_metrics m ON m.id=(SELECT id FROM post_metrics WHERE post_id=p.id ORDER BY collected_at DESC LIMIT 1) WHERE p.profile_id IN (${marks}) AND p.published_at>=UTC_TIMESTAMP()-INTERVAL 90 DAY) ranked WHERE ranked.profile_rank<=20 ORDER BY ranked.profile_id,ranked.engagement DESC`,ids);
  const history=await rows<RowDataPacket[]>('SELECT followers_count followers,engagement_rate engagementRate,collected_at collectedAt FROM profile_snapshots WHERE profile_id=? ORDER BY collected_at DESC LIMIT 12',[profileId]);
  const weekday=(value:any)=>new Intl.DateTimeFormat('pt-BR',{weekday:'long',timeZone:'America/Sao_Paulo'}).format(new Date(value));const hour=(value:any)=>new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',hour12:false,timeZone:'America/Sao_Paulo'}).format(new Date(value)).replace(' h','h');
  const benchmarks=analyzedProfiles.map((item:any)=>{const own=(posts as any[]).filter(post=>Number(post.profile_id)===Number(item.id));const formatMap=new Map<string,{format:string;posts:number;engagement:number}>();const windowMap=new Map<string,{day:string;time:string;posts:number;engagement:number}>();const hashtagMap=new Map<string,{hashtag:string;posts:number;engagement:number}>();for(const post of own){const format=post.content_surface==='Reel'||post.post_type==='Reel'?'Reel':post.post_type==='Sidecar'?'Carrossel':post.post_type;const f=formatMap.get(format)||{format,posts:0,engagement:0};f.posts++;f.engagement+=Number(post.engagement);formatMap.set(format,f);const day=weekday(post.published_at),time=hour(post.published_at),key=`${day}:${time}`;const w=windowMap.get(key)||{day,time,posts:0,engagement:0};w.posts++;w.engagement+=Number(post.engagement);windowMap.set(key,w);for(const raw of String(post.hashtags||'').split(',').filter(Boolean)){const hashtag=`#${raw.replace(/^#/,'')}`;const h=hashtagMap.get(hashtag)||{hashtag,posts:0,engagement:0};h.posts++;h.engagement+=Number(post.engagement);hashtagMap.set(hashtag,h)}}const average=(entry:{posts:number;engagement:number})=>entry.posts?Math.round(entry.engagement/entry.posts):0;return{role:Number(item.id)===profileId?'base':'comparison',profile:{...item,followerGrowth:Number(item.followers)-Number(item.firstFollowers||item.followers)},formats:[...formatMap.values()].map(entry=>({...entry,averageEngagement:average(entry)})).sort((a,b)=>b.averageEngagement-a.averageEngagement),postingWindows:[...windowMap.values()].filter(entry=>entry.posts>=2).map(entry=>({...entry,averageEngagement:average(entry)})).sort((a,b)=>b.averageEngagement-a.averageEngagement).slice(0,6),hashtags:[...hashtagMap.values()].map(entry=>({...entry,averageEngagement:average(entry)})).sort((a,b)=>b.averageEngagement-a.averageEngagement).slice(0,15),topPosts:own.slice(0,8)}});
  return{generatedAt:new Date().toISOString(),timezone:'America/Sao_Paulo',period:'Últimos 90 dias para conteúdo; métricas atuais dos perfis',comparisonScope:groupedIds.length?'Perfis que compartilham grupo de comparação com o perfil base':'Todos os perfis ativos (nenhum grupo compartilhado encontrado)',sample:{profiles:analyzedProfiles.length,posts:(posts as any[]).length},baseProfileId:profileId,history,benchmarks};
}
type AiJobRow=RowDataPacket&{id:number;profile_id:number;provider:AiProvider;model:string;status:'queued'|'running'|'succeeded'|'failed';analysis_id:number|null;error_message:string|null;created_by:number|null;started_at:Date|null;finished_at:Date|null;created_at:Date};
function publicAiJob(job:AiJobRow|undefined){return job?{id:Number(job.id),profileId:Number(job.profile_id),provider:job.provider,model:job.model,status:job.status,analysisId:job.analysis_id?Number(job.analysis_id):null,errorMessage:job.error_message,createdAt:job.created_at,startedAt:job.started_at,finishedAt:job.finished_at}:null}
let aiWorkerRunning=false;
async function processAiQueue(){if(aiWorkerRunning)return;aiWorkerRunning=true;try{while(true){const queued=await rows<AiJobRow[]>(`SELECT * FROM ai_analysis_jobs WHERE status='queued' ORDER BY created_at LIMIT 1`);const job=queued[0];if(!job)break;const [claimed]=await db.execute<ResultSetHeader>(`UPDATE ai_analysis_jobs SET status='running',started_at=UTC_TIMESTAMP(),error_message=NULL WHERE id=? AND status='queued'`,[job.id]);if(!claimed.affectedRows)continue;try{const setting=await getAiSettingsRow();const credentials=configuredAi(setting,job.provider);const snapshot=await aiSourceSnapshot(Number(job.profile_id));const analysis=await generateProfileAnalysis(job.provider,job.model,credentials.key,snapshot);await transaction(async connection=>{const [created]=await connection.execute<ResultSetHeader>('INSERT INTO ai_profile_analyses(profile_id,provider,model,analysis_json,source_snapshot,created_by) VALUES(?,?,?,?,?,?)',[job.profile_id,job.provider,job.model,JSON.stringify(analysis),JSON.stringify(snapshot),job.created_by]);await connection.execute(`UPDATE ai_analysis_jobs SET status='succeeded',analysis_id=?,finished_at=UTC_TIMESTAMP() WHERE id=?`,[created.insertId,job.id])});}catch(error:any){const message=error?.status?String(error.message):'Falha interna ao preparar ou salvar a análise.';await db.execute(`UPDATE ai_analysis_jobs SET status='failed',error_message=?,finished_at=UTC_TIMESTAMP() WHERE id=?`,[message,job.id]);console.error(`Falha na análise de IA #${job.id}:`,error)}}}finally{aiWorkerRunning=false}}
app.get('/api/ai/analysis/base',wrap(async(_req,res)=>{const setting=await getAiSettingsRow();const configuration=publicAiSettings(setting);if(!setting.base_profile_id)return res.json({configuration,analysis:null,job:null,message:'Defina um perfil base para gerar a análise.'});const [latest,jobRows]=await Promise.all([rows<RowDataPacket[]>('SELECT id,profile_id,provider,model,analysis_json,created_at FROM ai_profile_analyses WHERE profile_id=? ORDER BY created_at DESC LIMIT 1',[setting.base_profile_id]),rows<AiJobRow[]>('SELECT * FROM ai_analysis_jobs WHERE profile_id=? ORDER BY created_at DESC LIMIT 1',[setting.base_profile_id])]);const item:any=latest[0];res.json({configuration,job:publicAiJob(jobRows[0]),analysis:item?{id:item.id,profileId:item.profile_id,provider:item.provider,model:item.model,createdAt:item.created_at,...(typeof item.analysis_json==='string'?JSON.parse(item.analysis_json):item.analysis_json)}:null})}));
app.post('/api/ai/analyze-base',rateLimit({windowMs:60_000,limit:4}),wrap(async(req,res)=>{const setting=await getAiSettingsRow();if(!setting.ai_enabled)return res.status(400).json({message:'Ative a inteligência artificial em Configurações.'});if(!setting.base_profile_id)return res.status(400).json({message:'Defina um perfil base antes de gerar a análise.'});configuredAi(setting,setting.ai_provider);const result=await transaction(async connection=>{const [active]=await connection.execute<AiJobRow[]>(`SELECT * FROM ai_analysis_jobs WHERE profile_id=? AND status IN ('queued','running') ORDER BY created_at DESC LIMIT 1 FOR UPDATE`,[setting.base_profile_id]);if(active[0])return{job:active[0],reused:true};const model=setting.ai_provider==='openai'?setting.openai_model:setting.anthropic_model;const [created]=await connection.execute<ResultSetHeader>(`INSERT INTO ai_analysis_jobs(profile_id,provider,model,status,created_by) VALUES(?,?,?,'queued',?)`,[setting.base_profile_id,setting.ai_provider,model,req.user!.id]);const [jobs]=await connection.execute<AiJobRow[]>('SELECT * FROM ai_analysis_jobs WHERE id=?',[created.insertId]);return{job:jobs[0],reused:false}});void processAiQueue();res.status(202).json({job:publicAiJob(result.job),reused:result.reused,message:result.reused?'A análise já está sendo processada em segundo plano.':'Análise iniciada em segundo plano.'})}));
app.get('/api/profiles', wrap(async (req, res) => {
  const q = String(req.query.q || ''); const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 20));
  const profiles = await rows<RowDataPacket[]>(`SELECT p.*,s.followers_count,s.posts_count,s.engagement_rate,
    COALESCE((SELECT status FROM collection_batches b WHERE b.profile_id=p.id ORDER BY b.created_at DESC LIMIT 1),(SELECT status FROM apify_runs r WHERE r.profile_id=p.id ORDER BY r.created_at DESC LIMIT 1)) run_status
    FROM instagram_profiles p LEFT JOIN profile_snapshots s ON s.id=(SELECT id FROM profile_snapshots WHERE profile_id=p.id ORDER BY collected_at DESC LIMIT 1)
    WHERE p.username LIKE ? OR COALESCE(p.internal_name,'') LIKE ? ORDER BY p.created_at DESC LIMIT ${limit} OFFSET ${(page-1)*limit}`, [`%${q}%`,`%${q}%`]);
  const count = await rows<(RowDataPacket & { total:number })[]>('SELECT COUNT(*) total FROM instagram_profiles WHERE username LIKE ? OR COALESCE(internal_name,\'\') LIKE ?', [`%${q}%`,`%${q}%`]);
  res.json({ data: profiles, pagination: { page, limit, total: Number(count[0].total) } });
}));
app.post('/api/profiles', wrap(async (req, res) => {
  const input = profileSchema.parse(req.body); const username = normalizeUsername(input.username);
  if (!/^[a-z0-9._]{1,30}$/.test(username)) return res.status(400).json({ message: 'Username ou URL do Instagram inválido.' });
  try { const [result] = await db.execute<ResultSetHeader>('INSERT INTO instagram_profiles(username,internal_name,profile_url,created_by) VALUES(?,?,?,?)', [username,input.internalName || null,`https://www.instagram.com/${username}/`,req.user!.id]);
    res.status(201).json({ id:result.insertId, username, internal_name:input.internalName });
  } catch (error: any) { if (error.code === 'ER_DUP_ENTRY') return res.status(409).json({ message: 'Este perfil já está cadastrado.' }); throw error; }
}));
app.get('/api/profiles/:id', wrap(async (req, res) => { const found = await rows<RowDataPacket[]>('SELECT * FROM instagram_profiles WHERE id=?', [idOf(req)]); if (!found[0]) return res.status(404).json({message:'Perfil não encontrado.'}); res.json(found[0]); }));
app.put('/api/profiles/:id', wrap(async (req, res) => { const input = profileSchema.partial().parse(req.body); const fields:string[]=[]; const values:any[]=[];
  if (input.username) { const username=normalizeUsername(input.username); fields.push('username=?','profile_url=?'); values.push(username,`https://www.instagram.com/${username}/`); }
  if (input.internalName !== undefined) { fields.push('internal_name=?'); values.push(input.internalName); } if (input.isActive !== undefined) { fields.push('is_active=?'); values.push(input.isActive); }
  if (!fields.length) return res.status(400).json({message:'Nenhuma alteração enviada.'}); values.push(idOf(req)); await db.execute(`UPDATE instagram_profiles SET ${fields.join(',')} WHERE id=?`,values); res.status(204).end();
}));
app.delete('/api/profiles/:id', wrap(async (req,res) => { await db.execute('DELETE FROM instagram_profiles WHERE id=?',[idOf(req)]); res.status(204).end(); }));

async function getCollectionSettings(){const settings=await rows<(RowDataPacket&{collection_results_limit:number;collection_only_posts_newer_than:string;collection_posts_until:string|null})[]>(`SELECT collection_results_limit,collection_only_posts_newer_than,DATE_FORMAT(collection_posts_until,'%Y-%m-%d') collection_posts_until FROM workspace_settings WHERE id=1`);return {resultsLimit:Number(settings[0]?.collection_results_limit||100),onlyPostsNewerThan:String(settings[0]?.collection_only_posts_newer_than||'30 days'),postsUntil:settings[0]?.collection_posts_until||null};}
app.get('/api/collection-settings',wrap(async(_req,res)=>{res.json(await getCollectionSettings());}));
app.put('/api/collection-settings',wrap(async(req,res)=>{const input=collectionSettingsSchema.parse(req.body);await db.execute(`INSERT INTO workspace_settings(id,collection_results_limit,collection_only_posts_newer_than,collection_posts_until,updated_by) VALUES(1,?,?,?,?) ON DUPLICATE KEY UPDATE collection_results_limit=VALUES(collection_results_limit),collection_only_posts_newer_than=VALUES(collection_only_posts_newer_than),collection_posts_until=VALUES(collection_posts_until),updated_by=VALUES(updated_by)`,[input.resultsLimit,input.onlyPostsNewerThan,input.postsUntil||null,req.user!.id]);res.json({...input,postsUntil:input.postsUntil||null});}));

async function createRun(profileId:number, input:CollectionInput) {
  const reservation=await transaction(async connection=>{
    const [profiles]=await connection.execute<(RowDataPacket&{username:string})[]>('SELECT username FROM instagram_profiles WHERE id=? FOR UPDATE',[profileId]);
    if(!profiles[0]) throw Object.assign(new Error('Perfil não encontrado.'),{status:404});
    const [active]=await connection.execute<(RowDataPacket&{id:number;status:string})[]>(`SELECT id,status FROM apify_runs WHERE profile_id=? AND status IN ('pending','running') ORDER BY created_at DESC LIMIT 1`,[profileId]);
    if(active[0]) return {id:Number(active[0].id),username:profiles[0].username,status:active[0].status,reused:true};
    const [created]=await connection.execute<ResultSetHeader>('INSERT INTO apify_runs(profile_id,collection_type,requested_posts_limit,only_posts_newer_than,only_posts_older_than,status) VALUES(?,?,?,?,?,\'pending\')',[profileId,input.type,input.limit,input.newerThan,input.olderThan]);
    return {id:Number(created.insertId),username:profiles[0].username,status:'pending',reused:false};
  });
  if(reservation.reused)return reservation;
  try {
    const actor=await startActor(reservation.username,input.type,input.limit,input.newerThan);
    await db.execute('UPDATE apify_runs SET apify_run_id=?,apify_dataset_id=?,request_payload=?,status=\'running\',started_at=UTC_TIMESTAMP() WHERE id=?',[actor.runId,actor.datasetId,JSON.stringify({...actor.payload,onlyPostsOlderThan:input.olderThan}),reservation.id]);
    return {...reservation,status:'running'};
  } catch(error) {
    const message=String(error instanceof Error?error.message:error);
    await db.execute('UPDATE apify_runs SET status=\'failed\',finished_at=UTC_TIMESTAMP(),error_message=? WHERE id=?',[message,reservation.id]);
    throw Object.assign(new Error(`Não foi possível iniciar a coleta: ${message}`),{status:502});
  }
}
async function refreshBatchStatus(batchId:number){
  const children=await rows<(RowDataPacket&{status:string;error_message:string|null})[]>('SELECT status,error_message FROM apify_runs WHERE batch_id=?',[batchId]);
  if(!children.length)return 'pending';
  const statuses=children.map(child=>child.status);let status='running';
  if(statuses.every(value=>value==='succeeded'))status='succeeded';
  else if(statuses.some(value=>value==='pending'||value==='running'))status='running';
  else if(statuses.some(value=>value==='failed'))status='failed';
  else if(statuses.some(value=>value==='timed_out'))status='timed_out';
  else status='aborted';
  const error=children.find(child=>child.error_message)?.error_message||null;
  await db.execute(`UPDATE collection_batches SET status=?,started_at=COALESCE(started_at,UTC_TIMESTAMP()),finished_at=IF(?='running',NULL,UTC_TIMESTAMP()),error_message=? WHERE id=?`,[status,status,error,batchId]);
  return status;
}
async function createCollectionBatch(profileId:number,input:CollectionInput){
  const reservation=await transaction(async connection=>{
    const [profiles]=await connection.execute<(RowDataPacket&{username:string})[]>('SELECT username FROM instagram_profiles WHERE id=? FOR UPDATE',[profileId]);
    if(!profiles[0])throw Object.assign(new Error('Perfil não encontrado.'),{status:404});
    const [active]=await connection.execute<(RowDataPacket&{id:number;status:string})[]>(`SELECT id,status FROM collection_batches WHERE profile_id=? AND status IN ('pending','running') ORDER BY created_at DESC LIMIT 1`,[profileId]);
    if(active[0]){const [runs]=await connection.execute<(RowDataPacket&{id:number})[]>('SELECT id FROM apify_runs WHERE batch_id=? ORDER BY id',[active[0].id]);return {batchId:Number(active[0].id),ids:runs.map(run=>Number(run.id)),username:profiles[0].username,reused:true,runs:[] as {id:number;type:'profile_details'|'posts'|'stories';limit:number}[]};}
    const [batch]=await connection.execute<ResultSetHeader>('INSERT INTO collection_batches(profile_id,status) VALUES(?,\'pending\')',[profileId]);const batchId=Number(batch.insertId);
    const definitions:{type:'profile_details'|'posts'|'stories';limit:number}[]=[{type:'profile_details',limit:1},{type:'posts',limit:input.limit},{type:'stories',limit:Math.min(input.limit,50)}];const createdRuns:{id:number;type:'profile_details'|'posts'|'stories';limit:number}[]=[];
    for(const definition of definitions){const [created]=await connection.execute<ResultSetHeader>('INSERT INTO apify_runs(profile_id,batch_id,collection_type,requested_posts_limit,only_posts_newer_than,only_posts_older_than,status) VALUES(?,?,?,?,?,?,\'pending\')',[profileId,batchId,definition.type,definition.limit,input.newerThan,input.olderThan]);createdRuns.push({id:Number(created.insertId),...definition});}
    return {batchId,ids:createdRuns.map(run=>run.id),username:profiles[0].username,reused:false,runs:createdRuns};
  });
  if(reservation.reused)return reservation;
  await Promise.all(reservation.runs.map(async run=>{try{const actor=await startActor(reservation.username,run.type,run.limit,input.newerThan);await db.execute('UPDATE apify_runs SET apify_run_id=?,apify_dataset_id=?,request_payload=?,status=\'running\',started_at=UTC_TIMESTAMP() WHERE id=?',[actor.runId,actor.datasetId,JSON.stringify({...actor.payload,onlyPostsOlderThan:input.olderThan}),run.id]);}catch(error){await db.execute('UPDATE apify_runs SET status=\'failed\',finished_at=UTC_TIMESTAMP(),error_message=? WHERE id=?',[String(error instanceof Error?error.message:error),run.id]);}}));
  await refreshBatchStatus(reservation.batchId);return reservation;
}
app.post('/api/profiles/:id/collect', wrap(async(req,res)=>{ const requested=collectSchema.parse(req.body);const settings=await getCollectionSettings();const input:CollectionInput={...requested,limit:settings.resultsLimit,newerThan:settings.onlyPostsNewerThan,olderThan:settings.postsUntil};if(input.type==='full'){const batch=await createCollectionBatch(idOf(req),input);return res.status(batch.reused?200:202).json({...batch,settings});}const result=await createRun(idOf(req),input);res.status(result.reused?200:202).json({...result,settings}); }));
app.get('/api/runs', wrap(async(req,res)=>{ const status=String(req.query.status||''); const values:unknown[]=[]; const where=status?'WHERE r.status=?':''; if(status) values.push(status);
  res.json(await rows<RowDataPacket[]>(`SELECT r.*,p.username,p.internal_name,TIMESTAMPDIFF(SECOND,r.started_at,r.finished_at) duration_seconds FROM apify_runs r JOIN instagram_profiles p ON p.id=r.profile_id ${where} ORDER BY r.created_at DESC LIMIT 200`,values)); }));
app.delete('/api/runs', wrap(async(_req,res)=>{const result=await transaction(async c=>{const [active]=await c.execute<RowDataPacket[]>(`SELECT id FROM apify_runs WHERE status IN ('pending','running') FOR UPDATE`);if(active.length>0)throw Object.assign(new Error('Cancele ou aguarde as coletas em andamento antes de limpar todo o histórico.'),{status:409});const [deletedRuns]=await c.execute<ResultSetHeader>('DELETE FROM apify_runs');const [deletedBatches]=await c.execute<ResultSetHeader>('DELETE FROM collection_batches');return {runs:deletedRuns.affectedRows,batches:deletedBatches.affectedRows};});res.json({deleted:result});}));
app.delete('/api/collection-batches/:id', wrap(async(req,res)=>{const batchId=idOf(req);const deleted=await transaction(async c=>{const [batch]=await c.execute<RowDataPacket[]>('SELECT id FROM collection_batches WHERE id=? FOR UPDATE',[batchId]);if(!batch[0])throw Object.assign(new Error('Coleta não encontrada.'),{status:404});const [active]=await c.execute<RowDataPacket[]>(`SELECT id FROM apify_runs WHERE batch_id=? AND status IN ('pending','running') FOR UPDATE`,[batchId]);if(active.length>0)throw Object.assign(new Error('Cancele ou aguarde esta coleta antes de limpá-la.'),{status:409});const [runs]=await c.execute<ResultSetHeader>('DELETE FROM apify_runs WHERE batch_id=?',[batchId]);await c.execute('DELETE FROM collection_batches WHERE id=?',[batchId]);return runs.affectedRows;});res.json({deletedRuns:deleted});}));
app.delete('/api/runs/:id', wrap(async(req,res)=>{const runId=idOf(req);await transaction(async c=>{const [found]=await c.execute<(RowDataPacket&{status:string;batch_id:number|null})[]>('SELECT status,batch_id FROM apify_runs WHERE id=? FOR UPDATE',[runId]);if(!found[0])throw Object.assign(new Error('Coleta não encontrada.'),{status:404});if(['pending','running'].includes(found[0].status))throw Object.assign(new Error('Cancele ou aguarde esta coleta antes de limpá-la.'),{status:409});await c.execute('DELETE FROM apify_runs WHERE id=?',[runId]);if(found[0].batch_id)await c.execute('DELETE FROM collection_batches WHERE id=? AND NOT EXISTS(SELECT 1 FROM apify_runs WHERE batch_id=?)',[found[0].batch_id,found[0].batch_id]);});res.status(204).end();}));
app.get('/api/runs/:id', wrap(async(req,res)=>{ const data=await rows<RowDataPacket[]>('SELECT r.*,p.username FROM apify_runs r JOIN instagram_profiles p ON p.id=r.profile_id WHERE r.id=?',[idOf(req)]); if(!data[0]) return res.status(404).json({message:'Coleta não encontrada.'}); res.json(data[0]); }));

async function importRun(localRunId:number) {
  const runs = await rows<(RowDataPacket & {profile_id:number;apify_dataset_id:string;collection_type:string;only_posts_older_than:string|null})[]>('SELECT * FROM apify_runs WHERE id=?',[localRunId]); const initialRun=runs[0]; if(!initialRun) throw new Error('Coleta não encontrada.');
  const items=await getDataset(initialRun.apify_dataset_id);
  await transaction(async c=>{
    const [locked]=await c.execute<(RowDataPacket&{profile_id:number;status:string})[]>('SELECT * FROM apify_runs WHERE id=? FOR UPDATE',[localRunId]);
    const run=locked[0];if(!run)throw new Error('Coleta não encontrada.');if(run.status==='succeeded')return;
    const detail=items.find(i=>i.username && (i.followersCount!=null || i.followers!=null));
    if(detail){ await c.execute(`UPDATE instagram_profiles SET instagram_profile_id=?,full_name=?,biography=?,profile_picture_url=?,external_url=?,category=?,is_verified=?,is_private=?,last_collected_at=UTC_TIMESTAMP() WHERE id=?`,
      [detail.id||null,detail.fullName||null,detail.biography||null,detail.profilePicUrl||detail.profilePicUrlHD||null,detail.externalUrl||null,detail.businessCategoryName||detail.categoryName||null,Boolean(detail.verified),Boolean(detail.private),run.profile_id] as any[]); }
    const [previousSnapshots]=await c.execute<RowDataPacket[]>('SELECT followers_count FROM profile_snapshots WHERE profile_id=? ORDER BY collected_at DESC LIMIT 1',[run.profile_id]);
    const followerCount=Number(detail?.followersCount||detail?.followers||previousSnapshots[0]?.followers_count||0); let likesTotal=0,commentsTotal=0,postCount=0;
    for(const raw of items.filter(i=>i.type || i.shortCode || i.shortcode)) { const post=normalizePost(raw); if(!post.instagramPostId&&!post.shortcode) continue;
      if(initialRun.collection_type==='posts'&&initialRun.only_posts_older_than&&post.publishedAt){const end=new Date(`${String(initialRun.only_posts_older_than).slice(0,10)}T23:59:59.999Z`);if(new Date(post.publishedAt)>end)continue;}
      await c.execute(`INSERT INTO instagram_posts(profile_id,instagram_post_id,shortcode,post_type,content_surface,caption,post_url,display_url,video_url,published_at,duration_seconds,is_paid_partnership,comments_disabled,raw_data)
        VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE caption=VALUES(caption),post_type=VALUES(post_type),content_surface=VALUES(content_surface),post_url=VALUES(post_url),display_url=VALUES(display_url),video_url=VALUES(video_url),updated_at=CURRENT_TIMESTAMP`,
        [run.profile_id,post.instagramPostId,post.shortcode,post.type,post.surface,post.caption,post.postUrl,post.displayUrl,post.videoUrl,post.publishedAt,post.duration,post.paid,post.commentsDisabled,JSON.stringify(post.raw)]);
      const [found]=await c.execute<RowDataPacket[]>('SELECT id FROM instagram_posts WHERE profile_id=? AND (instagram_post_id=? OR shortcode=?) LIMIT 1',[run.profile_id,post.instagramPostId,post.shortcode]); const postId=Number(found[0].id); const metric=engagement(post.likes,post.comments,followerCount);
      await c.execute('INSERT IGNORE INTO post_metrics(post_id,apify_run_id,likes_count,comments_count,views_count,plays_count,engagement_count,engagement_rate) VALUES(?,?,?,?,?,?,?,?)',[postId,localRunId,post.likes,post.comments,post.views,post.plays,metric.count,metric.rate]);
      for(const tag of post.hashtags){ await c.execute('INSERT IGNORE INTO hashtags(name) VALUES(?)',[tag]); const [h]=await c.execute<RowDataPacket[]>('SELECT id FROM hashtags WHERE name=?',[tag]); await c.execute('INSERT IGNORE INTO post_hashtags(post_id,hashtag_id) VALUES(?,?)',[postId,h[0].id]); }
      const nestedComments=Array.isArray(raw.latestComments)?raw.latestComments:Array.isArray(raw.comments)?raw.comments:[];
      for(const item of nestedComments as Record<string,unknown>[]){ const commentId=String(item.id||item.commentId||'')||null; if(!commentId) continue;
        await c.execute(`INSERT IGNORE INTO instagram_comments(post_id,instagram_comment_id,text,owner_username,owner_full_name,owner_profile_picture_url,likes_count,replies_count,commented_at,raw_data)
          VALUES(?,?,?,?,?,?,?,?,?,?)`,[postId,commentId,item.text||item.commentText||null,item.ownerUsername||item.owner?.toString()||null,item.ownerFullName||null,item.ownerProfilePicUrl||null,Number(item.likesCount||0),Number(item.repliesCount||0),item.timestamp?new Date(String(item.timestamp)):null,JSON.stringify(item)] as any[]); }
      likesTotal+=post.likes; commentsTotal+=post.comments; postCount++;
    }
    const avgLikes=postCount?likesTotal/postCount:0,avgComments=postCount?commentsTotal/postCount:0,avgEng=avgLikes+avgComments,rate=followerCount?avgEng/followerCount*100:0;
    await c.execute('INSERT INTO profile_snapshots(profile_id,followers_count,follows_count,posts_count,average_likes,average_comments,average_engagement,engagement_rate) VALUES(?,?,?,?,?,?,?,?)',[run.profile_id,followerCount,Number(detail?.followsCount||detail?.following||0),Number(detail?.postsCount||postCount),avgLikes,avgComments,avgEng,rate]);
    await c.execute('UPDATE instagram_profiles SET last_collected_at=UTC_TIMESTAMP() WHERE id=?',[run.profile_id]);
    await c.execute('UPDATE apify_runs SET status=\'succeeded\',finished_at=UTC_TIMESTAMP(),result_summary=? WHERE id=?',[JSON.stringify({itemsProcessed:items.length,postsProcessed:postCount}),localRunId]);
  });
}
async function refreshLocalRun(localId:number){ const found=await rows<(RowDataPacket & {apify_run_id:string;status:string;batch_id:number|null})[]>('SELECT * FROM apify_runs WHERE id=?',[localId]); if(!found[0]) throw Object.assign(new Error('Coleta não encontrada.'),{status:404}); if(!found[0].apify_run_id) throw Object.assign(new Error('Execução não iniciada.'),{status:400});
  const remote=await getRun(found[0].apify_run_id); const mapped:{[key:string]:string}={READY:'running',RUNNING:'running',SUCCEEDED:'succeeded',FAILED:'failed',ABORTED:'aborted',TIMED_OUT:'timed_out'}; const status=mapped[remote.status]||'running';
  if(status==='succeeded'&&found[0].status!=='succeeded'){
    try{await importRun(localId);}catch(error){const message=`A Apify concluiu, mas a importação falhou: ${String(error instanceof Error?error.message:error)}`;await db.execute('UPDATE apify_runs SET status=\'failed\',finished_at=UTC_TIMESTAMP(),error_message=? WHERE id=?',[message,localId]);if(found[0].batch_id)await refreshBatchStatus(Number(found[0].batch_id));throw Object.assign(new Error(message),{status:500});}
  }else await db.execute('UPDATE apify_runs SET status=?,finished_at=IF(?=\'running\',NULL,UTC_TIMESTAMP()),error_message=? WHERE id=?',[status,status,remote.statusMessage||null,localId]);if(found[0].batch_id)await refreshBatchStatus(Number(found[0].batch_id));return status; }
app.post('/api/runs/:id/refresh', wrap(async(req,res)=>{ res.json({status:await refreshLocalRun(idOf(req))}); }));
app.post('/api/runs/:id/retry', wrap(async(req,res)=>{ const run=await rows<(RowDataPacket & {profile_id:number;collection_type:any;requested_posts_limit:number;only_posts_newer_than:string;only_posts_older_than:string|null})[]>('SELECT * FROM apify_runs WHERE id=?',[idOf(req)]); if(!run[0]) return res.status(404).json({message:'Coleta não encontrada.'}); const result=await createRun(run[0].profile_id,{type:run[0].collection_type,limit:run[0].requested_posts_limit,newerThan:run[0].only_posts_newer_than,olderThan:run[0].only_posts_older_than}); res.status(result.reused?200:202).json(result); }));
app.post('/api/runs/:id/abort', wrap(async(req,res)=>{ const run=await rows<(RowDataPacket & {apify_run_id:string;batch_id:number|null})[]>('SELECT * FROM apify_runs WHERE id=?',[idOf(req)]); if(run[0]?.apify_run_id) await abortRun(run[0].apify_run_id); await db.execute('UPDATE apify_runs SET status=\'aborted\',finished_at=UTC_TIMESTAMP() WHERE id=?',[idOf(req)]);if(run[0]?.batch_id)await refreshBatchStatus(Number(run[0].batch_id));res.status(204).end(); }));

const dashboardSql=`SELECT p.*,s.followers_count,s.follows_count,s.posts_count,s.average_likes,s.average_comments,s.average_engagement,s.engagement_rate,
  (SELECT followers_count FROM profile_snapshots WHERE profile_id=p.id AND followers_count>0 ORDER BY collected_at ASC LIMIT 1) first_followers
  FROM instagram_profiles p LEFT JOIN profile_snapshots s ON s.id=(SELECT id FROM profile_snapshots WHERE profile_id=p.id ORDER BY collected_at DESC LIMIT 1) WHERE p.id=?`;
app.get('/api/dashboard/summary', wrap(async(_req,res)=>{ const summary=await rows<RowDataPacket[]>(`SELECT COUNT(*) profiles,COALESCE(SUM(x.followers_count),0) followers,COALESCE(AVG(x.engagement_rate),0) engagement_rate,(SELECT COUNT(*) FROM instagram_posts) posts,(SELECT COUNT(*) FROM apify_runs WHERE status='running') running FROM instagram_profiles p LEFT JOIN profile_snapshots x ON x.id=(SELECT id FROM profile_snapshots WHERE profile_id=p.id ORDER BY collected_at DESC LIMIT 1)`); const top=await rows<RowDataPacket[]>(`${dashboardSql.replace('WHERE p.id=?','')} ORDER BY s.engagement_rate DESC LIMIT 6`); res.json({summary:summary[0],profiles:top}); }));
app.get('/api/dashboard/strategy', wrap(async(req,res)=>{
  const configured=await rows<(RowDataPacket&{base_profile_id:number|null})[]>('SELECT base_profile_id FROM workspace_settings WHERE id=1');
  const profiles=await rows<RowDataPacket[]>(`SELECT p.id,p.username,p.internal_name,p.full_name,p.profile_picture_url,p.last_collected_at,
    COALESCE(s.followers_count,0) followers_count,COALESCE(s.posts_count,0) posts_count,COALESCE(s.average_likes,0) average_likes,
    COALESCE(s.average_comments,0) average_comments,COALESCE(s.average_engagement,0) average_engagement,COALESCE(s.engagement_rate,0) engagement_rate,
    COALESCE((SELECT followers_count FROM profile_snapshots WHERE profile_id=p.id AND followers_count>0 ORDER BY collected_at ASC LIMIT 1),0) first_followers,
    (SELECT COUNT(*) FROM instagram_posts ip WHERE ip.profile_id=p.id AND ip.published_at>=UTC_TIMESTAMP()-INTERVAL 30 DAY) recent_posts
    FROM instagram_profiles p LEFT JOIN profile_snapshots s ON s.id=(SELECT id FROM profile_snapshots WHERE profile_id=p.id ORDER BY collected_at DESC LIMIT 1)
    WHERE p.is_active=1 ORDER BY p.created_at`);
  const formats=await rows<RowDataPacket[]>(`SELECT p.profile_id,p.post_type,COUNT(*) posts,AVG(COALESCE(m.engagement_count,0)) average_engagement
    FROM instagram_posts p LEFT JOIN post_metrics m ON m.id=(SELECT id FROM post_metrics WHERE post_id=p.id ORDER BY collected_at DESC LIMIT 1)
    GROUP BY p.profile_id,p.post_type ORDER BY average_engagement DESC`);
  const baseId=Number(configured[0]?.base_profile_id||0)||null; const requestedId=Number(req.query.profileId||0); const selected=profiles.find((p:any)=>Number(p.id)===(requestedId||baseId||Number(profiles[0]?.id)));
  if(!selected) return res.json({profiles:[],baseProfileId:baseId,selected:null,competitors:[],recommendations:[]});
  const enriched=profiles.map((profile:any)=>{const profileFormats=formats.filter((f:any)=>Number(f.profile_id)===Number(profile.id));const growth=Number(profile.followers_count)-Number(profile.first_followers);return {...profile,growth,growth_percent:Number(profile.first_followers)>0?growth/Number(profile.first_followers)*100:0,best_format:profileFormats[0]?.post_type||null,best_format_engagement:Number(profileFormats[0]?.average_engagement||0)};});
  const current=enriched.find((p:any)=>Number(p.id)===Number(selected.id)); const competitors=enriched.filter((p:any)=>Number(p.id)!==Number(current.id));
  const avg=(key:string)=>competitors.length?competitors.reduce((sum:number,p:any)=>sum+Number(p[key]||0),0)/competitors.length:0; const best=(key:string)=>competitors.length?Math.max(...competitors.map((p:any)=>Number(p[key]||0))):0;
  const recommendations:any[]=[];
  if(!current.last_collected_at) recommendations.push({priority:'high',category:'Dados',title:'Realize a primeira coleta',insight:'Ainda não há dados do Instagram Scraper para este perfil.',action:'Abra o perfil e use “Atualizar Instagram” antes de comparar o desempenho.'});
  else {
    const competitorEngagement=avg('engagement_rate'); if(competitorEngagement>Number(current.engagement_rate)) recommendations.push({priority:'high',category:'Engajamento',title:'Fechar a diferença de engajamento',insight:`O perfil está ${(competitorEngagement-Number(current.engagement_rate)).toFixed(2)} p.p. abaixo da média dos concorrentes.`,action:'Repita temas e formatos dos posts com maior número de comentários e inclua uma chamada clara para interação.'}); else recommendations.push({priority:'positive',category:'Engajamento',title:'Transformar vantagem em consistência',insight:'A taxa de engajamento está acima da média dos concorrentes.',action:'Mantenha o padrão editorial dos conteúdos líderes e teste variações do mesmo tema.'});
    const competitorFrequency=best('recent_posts'); if(competitorFrequency>Number(current.recent_posts)) recommendations.push({priority:'medium',category:'Frequência',title:'Aumentar a cadência de publicação',insight:`O concorrente mais ativo publicou ${competitorFrequency} vezes nos últimos 30 dias; este perfil publicou ${current.recent_posts}.`,action:`Planeje ao menos ${Math.ceil((competitorFrequency-Number(current.recent_posts))/4)} publicação adicional por semana.`});
    const competitorLikes=avg('average_likes'); if(competitorLikes>Number(current.average_likes)) recommendations.push({priority:'medium',category:'Conteúdo',title:'Elevar o potencial de alcance',insight:`A média de curtidas está ${Math.round(competitorLikes-Number(current.average_likes))} abaixo dos concorrentes.`,action:`Priorize ${competitors.sort((a:any,b:any)=>b.best_format_engagement-a.best_format_engagement)[0]?.best_format||'o formato líder'} e adapte os assuntos que já geraram maior engajamento.`});
    if(current.growth<avg('growth')) recommendations.push({priority:'low',category:'Crescimento',title:'Converter engajamento em seguidores',insight:'O crescimento está abaixo da média do grupo monitorado.',action:'Inclua propostas de valor claras no perfil e chamadas para seguir em conteúdos de maior alcance.'});
  }
  const maxValues={followers_count:Math.max(1,...enriched.map((p:any)=>Number(p.followers_count))),engagement_rate:Math.max(1,...enriched.map((p:any)=>Number(p.engagement_rate))),recent_posts:Math.max(1,...enriched.map((p:any)=>Number(p.recent_posts))),average_likes:Math.max(1,...enriched.map((p:any)=>Number(p.average_likes))),growth:Math.max(1,...enriched.map((p:any)=>Math.max(0,Number(p.growth))))};
  const score=(profile:any)=>[{metric:'Audiência',score:Number(profile.followers_count)/maxValues.followers_count*100},{metric:'Engajamento',score:Number(profile.engagement_rate)/maxValues.engagement_rate*100},{metric:'Frequência',score:Number(profile.recent_posts)/maxValues.recent_posts*100},{metric:'Curtidas',score:Number(profile.average_likes)/maxValues.average_likes*100},{metric:'Crescimento',score:Math.max(0,Number(profile.growth))/maxValues.growth*100}];
  res.json({profiles:enriched,baseProfileId:baseId,selected:current,competitors,recommendations:recommendations.slice(0,4),scores:enriched.map((p:any)=>({id:p.id,username:p.username,values:score(p)}))});
}));
app.post('/api/profiles/:id/set-base', wrap(async(req,res)=>{const profileId=idOf(req);const found=await rows<RowDataPacket[]>('SELECT id FROM instagram_profiles WHERE id=?',[profileId]);if(!found[0])return res.status(404).json({message:'Perfil não encontrado.'});await db.execute(`INSERT INTO workspace_settings(id,base_profile_id,updated_by) VALUES(1,?,?) ON DUPLICATE KEY UPDATE base_profile_id=VALUES(base_profile_id),updated_by=VALUES(updated_by)`,[profileId,req.user!.id]);res.json({baseProfileId:profileId});}));
app.get('/api/profiles/:id/dashboard', wrap(async(req,res)=>{ const id=idOf(req); const profile=await rows<RowDataPacket[]>(dashboardSql,[id]); const history=await rows<RowDataPacket[]>('SELECT followers_count,average_engagement,engagement_rate,collected_at FROM profile_snapshots WHERE profile_id=? ORDER BY collected_at',[id]); const formats=await rows<RowDataPacket[]>(`SELECT p.post_type name,COUNT(*) posts,AVG(m.engagement_count) engagement FROM instagram_posts p LEFT JOIN post_metrics m ON m.id=(SELECT id FROM post_metrics WHERE post_id=p.id ORDER BY collected_at DESC LIMIT 1) WHERE p.profile_id=? GROUP BY p.post_type`,[id]); const topPosts=await rows<RowDataPacket[]>(`SELECT p.*,m.likes_count,m.comments_count,m.views_count,m.plays_count,m.engagement_rate FROM instagram_posts p LEFT JOIN post_metrics m ON m.id=(SELECT id FROM post_metrics WHERE post_id=p.id ORDER BY collected_at DESC LIMIT 1) WHERE p.profile_id=? ORDER BY m.engagement_count DESC LIMIT 8`,[id]); res.json({profile:profile[0],history,formats,topPosts}); }));
app.get('/api/profiles/:id/content-dashboard', wrap(async(req,res)=>{
  const id=idOf(req); const from=String(req.query.from||''); const to=String(req.query.to||''); const type=String(req.query.type||''); const search=String(req.query.search||'').trim();
  const values:any[]=[id]; let where='p.profile_id=?';
  if(from){ where+=' AND p.published_at>=?'; values.push(`${from} 00:00:00`); }
  if(to){ where+=' AND p.published_at<=?'; values.push(`${to} 23:59:59`); }
  if(type){ where+=' AND p.post_type=?'; values.push(type); }
  if(search){ where+=' AND (p.caption LIKE ? OR EXISTS(SELECT 1 FROM post_hashtags px JOIN hashtags hx ON hx.id=px.hashtag_id WHERE px.post_id=p.id AND hx.name LIKE ?))'; values.push(`%${search}%`,`%${search.replace(/^#/,'')}%`); }
  const profile=(await rows<RowDataPacket[]>(dashboardSql,[id]))[0]; if(!profile) return res.status(404).json({message:'Perfil não encontrado.'});
  const posts=await rows<RowDataPacket[]>(`SELECT p.id,p.shortcode,p.post_type,p.caption,p.post_url,p.display_url,p.published_at,p.duration_seconds,
    COALESCE(m.likes_count,0) likes_count,COALESCE(m.comments_count,0) comments_count,COALESCE(m.views_count,0) views_count,
    COALESCE(m.plays_count,0) plays_count,COALESCE(m.engagement_count,0) engagement_count,COALESCE(m.engagement_rate,0) engagement_rate,
    COALESCE((SELECT GROUP_CONCAT(h.name ORDER BY h.name SEPARATOR ',') FROM post_hashtags ph JOIN hashtags h ON h.id=ph.hashtag_id WHERE ph.post_id=p.id),'') hashtags
    FROM instagram_posts p LEFT JOIN post_metrics m ON m.id=(SELECT id FROM post_metrics WHERE post_id=p.id ORDER BY collected_at DESC LIMIT 1)
    WHERE ${where} ORDER BY p.published_at DESC LIMIT 1000`,values);
  const totals=posts.reduce((a:any,p:any)=>{a.likes+=Number(p.likes_count);a.comments+=Number(p.comments_count);a.views+=Number(p.views_count);a.plays+=Number(p.plays_count);a.engagement+=Number(p.engagement_count);return a;},{likes:0,comments:0,views:0,plays:0,engagement:0});
  const buckets=(keyOf:(post:any)=>string)=>{const map=new Map<string,any>(); for(const post of posts){const key=keyOf(post); const item=map.get(key)||{key,posts:0,likes:0,comments:0,views:0,plays:0,engagement:0};item.posts++;item.likes+=Number(post.likes_count);item.comments+=Number(post.comments_count);item.views+=Number(post.views_count);item.plays+=Number(post.plays_count);item.engagement+=Number(post.engagement_count);map.set(key,item);}return [...map.values()];};
  const monthly=buckets(p=>{const d=new Date(p.published_at);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}).sort((a,b)=>a.key.localeCompare(b.key));
  const formats=buckets(p=>p.post_type).map(x=>({...x,averageEngagement:x.posts?x.engagement/x.posts:0})).sort((a,b)=>b.averageEngagement-a.averageEngagement);
  const weekdaysNames=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb']; const weekdays=buckets(p=>weekdaysNames[new Date(p.published_at).getUTCDay()]).map(x=>({...x,order:weekdaysNames.indexOf(x.key),averageEngagement:x.posts?x.engagement/x.posts:0})).sort((a,b)=>a.order-b.order);
  const hashtagMap=new Map<string,any>(); for(const post of posts){for(const tag of String(post.hashtags||'').split(',').filter(Boolean)){const item=hashtagMap.get(tag)||{name:tag,uses:0,engagement:0};item.uses++;item.engagement+=Number(post.engagement_count);hashtagMap.set(tag,item);}}
  const hashtags=[...hashtagMap.values()].sort((a,b)=>b.engagement-a.engagement).slice(0,20); const ranked=[...posts].sort((a:any,b:any)=>Number(b.engagement_count)-Number(a.engagement_count));
  const days=posts.length?Math.max(1,(Math.max(...posts.map((p:any)=>+new Date(p.published_at)))-Math.min(...posts.map((p:any)=>+new Date(p.published_at))))/86400000):0;
  res.json({profile,summary:{posts:posts.length,...totals,averageEngagement:posts.length?totals.engagement/posts.length:0,averageLikes:posts.length?totals.likes/posts.length:0,averageComments:posts.length?totals.comments/posts.length:0,frequencyPerWeek:days?posts.length/days*7:posts.length},monthly,formats,weekdays,hashtags,posts:ranked,
    insights:{bestFormat:formats[0]?.key||null,bestDay:[...weekdays].sort((a,b)=>b.averageEngagement-a.averageEngagement)[0]?.key||null,topPost:ranked[0]||null}});
}));
app.get('/api/profiles/:id/posts', wrap(async(req,res)=>{ const id=idOf(req),page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(1,Number(req.query.limit)||20)); const type=String(req.query.type||''),search=String(req.query.search||''); const values:unknown[]=[id]; let where='p.profile_id=?'; if(type){where+=' AND p.post_type=?';values.push(type);} if(search){where+=' AND p.caption LIKE ?';values.push(`%${search}%`);} const data=await rows<RowDataPacket[]>(`SELECT p.*,m.likes_count,m.comments_count,m.views_count,m.plays_count,m.engagement_rate FROM instagram_posts p LEFT JOIN post_metrics m ON m.id=(SELECT id FROM post_metrics WHERE post_id=p.id ORDER BY collected_at DESC LIMIT 1) WHERE ${where} ORDER BY p.published_at DESC LIMIT ${limit} OFFSET ${(page-1)*limit}`,values); res.json({data,pagination:{page,limit}}); }));
app.get('/api/profiles/:id/hashtags', wrap(async(req,res)=>{ res.json(await rows<RowDataPacket[]>(`SELECT h.name,COUNT(*) uses,AVG(m.engagement_count) average_engagement FROM post_hashtags ph JOIN hashtags h ON h.id=ph.hashtag_id JOIN instagram_posts p ON p.id=ph.post_id LEFT JOIN post_metrics m ON m.id=(SELECT id FROM post_metrics WHERE post_id=p.id ORDER BY collected_at DESC LIMIT 1) WHERE p.profile_id=? GROUP BY h.id ORDER BY average_engagement DESC LIMIT 50`,[idOf(req)])); }));
app.get('/api/profiles/:id/history', wrap(async(req,res)=>{ res.json(await rows<RowDataPacket[]>('SELECT * FROM profile_snapshots WHERE profile_id=? ORDER BY collected_at',[idOf(req)])); }));
app.get('/api/posts/:id/dashboard', wrap(async(req,res)=>{
  const postId=idOf(req);const posts=await rows<RowDataPacket[]>(`SELECT p.*,pr.username,pr.full_name,pr.profile_picture_url,
    COALESCE(m.likes_count,0) likes_count,COALESCE(m.comments_count,0) comments_count,COALESCE(m.views_count,0) views_count,
    COALESCE(m.plays_count,0) plays_count,COALESCE(m.engagement_count,0) engagement_count,COALESCE(m.engagement_rate,0) engagement_rate,
    COALESCE((SELECT GROUP_CONCAT(h.name ORDER BY h.name SEPARATOR ',') FROM post_hashtags ph JOIN hashtags h ON h.id=ph.hashtag_id WHERE ph.post_id=p.id),'') hashtags,
    COALESCE((SELECT followers_count FROM profile_snapshots WHERE profile_id=p.profile_id ORDER BY collected_at DESC LIMIT 1),0) followers_count
    FROM instagram_posts p JOIN instagram_profiles pr ON pr.id=p.profile_id
    LEFT JOIN post_metrics m ON m.id=(SELECT id FROM post_metrics WHERE post_id=p.id ORDER BY collected_at DESC LIMIT 1) WHERE p.id=?`,[postId]);
  const post=posts[0];if(!post)return res.status(404).json({message:'Publicação não encontrada.'});
  const history=await rows<RowDataPacket[]>('SELECT likes_count,comments_count,views_count,plays_count,engagement_count,engagement_rate,collected_at FROM post_metrics WHERE post_id=? ORDER BY collected_at',[postId]);
  const comments=await rows<RowDataPacket[]>('SELECT id,text,owner_username,owner_full_name,owner_profile_picture_url,likes_count,replies_count,commented_at FROM instagram_comments WHERE post_id=? ORDER BY commented_at DESC LIMIT 100',[postId]);
  const ranking=await rows<(RowDataPacket&{position:number;total:number})[]>(`SELECT 1+SUM(CASE WHEN latest.engagement_count>? THEN 1 ELSE 0 END) position,COUNT(*) total FROM (
    SELECT ip.id,COALESCE((SELECT engagement_count FROM post_metrics WHERE post_id=ip.id ORDER BY collected_at DESC LIMIT 1),0) engagement_count
    FROM instagram_posts ip WHERE ip.profile_id=?) latest`,[Number(post.engagement_count),Number(post.profile_id)]);
  const first=history[0]||{},latest=history[history.length-1]||{};const daysOnline=Math.max(1,Math.ceil((Date.now()-new Date(post.published_at).getTime())/86400000));
  const growth={likes:Number(latest.likes_count||0)-Number(first.likes_count||0),comments:Number(latest.comments_count||0)-Number(first.comments_count||0),views:Number(latest.views_count||0)-Number(first.views_count||0),plays:Number(latest.plays_count||0)-Number(first.plays_count||0),engagement:Number(latest.engagement_count||0)-Number(first.engagement_count||0)};
  res.json({post,history,comments,growth,ranking:ranking[0],daysOnline,engagementPerDay:Number(post.engagement_count)/daysOnline,historyNotice:history.length<2?'A evolução começará a aparecer após uma nova coleta deste perfil.':'Cada ponto representa uma coleta real do Instagram Scraper.'});
}));

app.post('/api/comparisons/preview', wrap(async(req,res)=>{ const ids=z.object({profileIds:z.array(z.number().int().positive()).min(2).max(10)}).parse(req.body).profileIds; const marks=ids.map(()=>'?').join(','); const data=await rows<RowDataPacket[]>(`${dashboardSql.replace('WHERE p.id=?',`WHERE p.id IN (${marks})`)}`,ids); const history=await rows<RowDataPacket[]>(`SELECT s.*,p.username FROM profile_snapshots s JOIN instagram_profiles p ON p.id=s.profile_id WHERE s.profile_id IN (${marks}) ORDER BY s.collected_at`,ids); res.json({profiles:data,history}); }));
app.get('/api/comparisons/dashboard', wrap(async(req,res)=>{
  const allProfiles=await rows<RowDataPacket[]>(`SELECT p.id,p.username,p.full_name,p.internal_name,p.profile_picture_url,
    COALESCE(s.followers_count,0) followers_count,COALESCE(s.engagement_rate,0) current_engagement_rate
    FROM instagram_profiles p LEFT JOIN profile_snapshots s ON s.id=(SELECT id FROM profile_snapshots WHERE profile_id=p.id ORDER BY collected_at DESC LIMIT 1)
    WHERE p.is_active=1 ORDER BY p.created_at`);
  const setting=await rows<(RowDataPacket&{base_profile_id:number|null})[]>('SELECT base_profile_id FROM workspace_settings WHERE id=1'); const baseProfileId=Number(setting[0]?.base_profile_id||0)||null;
  const requested=String(req.query.profileIds||'').split(',').map(Number).filter(Number.isInteger).filter(id=>allProfiles.some((p:any)=>Number(p.id)===id));
  const ids=[...new Set([...(baseProfileId?[baseProfileId]:[]),...(requested.length?requested:allProfiles.map((p:any)=>Number(p.id)))])].slice(0,10);
  const period=z.enum(['day','week','month','custom']).catch('month').parse(req.query.period); const now=new Date(); let from=new Date(now); let to=new Date(now);
  if(period==='day') from.setUTCHours(0,0,0,0); else if(period==='week') from=new Date(now.getTime()-6*86400000); else if(period==='month') from=new Date(now.getTime()-29*86400000); else {from=new Date(String(req.query.from||''));to=new Date(String(req.query.to||''));if(Number.isNaN(+from)||Number.isNaN(+to))return res.status(400).json({message:'Informe data inicial e final válidas.'});}
  from.setUTCHours(0,0,0,0);to.setUTCHours(23,59,59,999);if(to<from)return res.status(400).json({message:'A data final deve ser posterior à inicial.'});if((+to-+from)/86400000>366)return res.status(400).json({message:'O período máximo é de 366 dias.'});
  if(!ids.length)return res.json({profiles:allProfiles,selectedProfiles:[],baseProfileId,period:{type:period,from,to},summaries:[],daily:[],formats:[],weekdays:[],topPosts:[]});
  const marks=ids.map(()=>'?').join(','); const selectedProfiles=allProfiles.filter((p:any)=>ids.includes(Number(p.id)));
  const posts=await rows<RowDataPacket[]>(`SELECT p.id,p.profile_id,p.shortcode,p.post_type,p.content_surface,p.caption,p.post_url,p.display_url,p.published_at,
    COALESCE(m.likes_count,0) likes_count,COALESCE(m.comments_count,0) comments_count,COALESCE(m.views_count,0) views_count,
    COALESCE(m.plays_count,0) plays_count,COALESCE(m.engagement_count,0) engagement_count
    FROM instagram_posts p LEFT JOIN post_metrics m ON m.id=(SELECT id FROM post_metrics WHERE post_id=p.id ORDER BY collected_at DESC LIMIT 1)
    WHERE p.profile_id IN (${marks}) AND p.published_at BETWEEN ? AND ? ORDER BY p.published_at`,[...ids,from,to]);
  const days=Math.max(1,Math.floor((+to-+from)/86400000)+1); const weekdaysNames=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
  const label=(post:any)=>post.content_surface==='Story'?'Story':post.content_surface==='Reel'||post.post_type==='Reel'?'Reel':post.post_type==='Sidecar'?'Carrossel':post.post_type==='Image'?'Imagem':post.post_type==='Video'?'Vídeo':'Outro';
  const dailyMap=new Map<string,any>(); const formatMap=new Map<string,any>(); const weekdayMap=new Map<string,any>();
  for(const post of posts as any[]){const username=selectedProfiles.find((p:any)=>Number(p.id)===Number(post.profile_id))?.username||String(post.profile_id);const dateKey=new Date(post.published_at).toISOString().slice(0,10);const dKey=`${post.profile_id}:${dateKey}`;const daily=dailyMap.get(dKey)||{date:dateKey,profileId:Number(post.profile_id),username,posts:0,engagement:0,likes:0,comments:0,plays:0,views:0,reels:0,stories:0};daily.posts++;daily.engagement+=Number(post.engagement_count);daily.likes+=Number(post.likes_count);daily.comments+=Number(post.comments_count);daily.plays+=Number(post.plays_count);daily.views+=Number(post.views_count);if(label(post)==='Reel')daily.reels++;if(label(post)==='Story')daily.stories++;dailyMap.set(dKey,daily);
    const format=label(post),fKey=`${post.profile_id}:${format}`;const f=formatMap.get(fKey)||{profileId:Number(post.profile_id),username,format,posts:0,engagement:0,likes:0,comments:0,plays:0,views:0};f.posts++;f.engagement+=Number(post.engagement_count);f.likes+=Number(post.likes_count);f.comments+=Number(post.comments_count);f.plays+=Number(post.plays_count);f.views+=Number(post.views_count);formatMap.set(fKey,f);
    const weekday=weekdaysNames[new Date(post.published_at).getUTCDay()],wKey=`${post.profile_id}:${weekday}`;const w=weekdayMap.get(wKey)||{profileId:Number(post.profile_id),username,weekday,order:weekdaysNames.indexOf(weekday),posts:0,engagement:0};w.posts++;w.engagement+=Number(post.engagement_count);weekdayMap.set(wKey,w);}
  const daily:any[]=[];for(const id of ids){const username=selectedProfiles.find((p:any)=>Number(p.id)===id)?.username;for(let cursor=new Date(from);cursor<=to;cursor=new Date(cursor.getTime()+86400000)){const key=cursor.toISOString().slice(0,10);daily.push(dailyMap.get(`${id}:${key}`)||{date:key,profileId:id,username,posts:0,engagement:0,likes:0,comments:0,plays:0,views:0,reels:0,stories:0});}}
  const formats=[...formatMap.values()].map((f:any)=>({...f,averageEngagement:f.posts?f.engagement/f.posts:0}));const weekdays=[...weekdayMap.values()].map((w:any)=>({...w,averageEngagement:w.posts?w.engagement/w.posts:0}));
  const summaries=selectedProfiles.map((profile:any)=>{const own=(posts as any[]).filter(p=>Number(p.profile_id)===Number(profile.id));const sum=(key:string)=>own.reduce((total,p)=>total+Number(p[key]||0),0);const ownFormats=formats.filter((f:any)=>f.profileId===Number(profile.id)).sort((a:any,b:any)=>b.averageEngagement-a.averageEngagement);const ownDays=weekdays.filter((w:any)=>w.profileId===Number(profile.id)).sort((a:any,b:any)=>b.averageEngagement-a.averageEngagement);const engagement=sum('engagement_count');return {...profile,posts:own.length,reels:own.filter(p=>label(p)==='Reel').length,stories:own.filter(p=>label(p)==='Story').length,feed:own.filter(p=>!['Reel','Story'].includes(label(p))).length,likes:sum('likes_count'),comments:sum('comments_count'),plays:sum('plays_count'),views:sum('views_count'),engagement,averageEngagement:own.length?engagement/own.length:0,averageLikes:own.length?sum('likes_count')/own.length:0,averageComments:own.length?sum('comments_count')/own.length:0,engagementRate:own.length&&Number(profile.followers_count)?engagement/own.length/Number(profile.followers_count)*100:0,publicationsPerWeek:own.length/days*7,bestFormat:ownFormats[0]?.format||null,bestDay:ownDays[0]?.weekday||null};});
  const topPosts=ids.flatMap(id=>(posts as any[]).filter(p=>Number(p.profile_id)===id).sort((a,b)=>Number(b.engagement_count)-Number(a.engagement_count)).slice(0,4).map(p=>({...p,username:selectedProfiles.find((x:any)=>Number(x.id)===id)?.username,format:label(p)})));
  const top10=(posts as any[]).sort((a,b)=>Number(b.engagement_count)-Number(a.engagement_count)).slice(0,10).map((post,index)=>({...post,position:index+1,username:selectedProfiles.find((p:any)=>Number(p.id)===Number(post.profile_id))?.username,format:label(post)}));
  res.json({profiles:allProfiles,selectedProfiles,baseProfileId,period:{type:period,from,to,days},summaries,daily,formats,weekdays,topPosts,top10,
    posts:(posts as any[]).map(post=>({...post,username:selectedProfiles.find((p:any)=>Number(p.id)===Number(post.profile_id))?.username,format:label(post)}))});
}));
app.post('/api/comparisons', wrap(async(req,res)=>{ const input=z.object({name:z.string().min(2),description:z.string().optional(),profileIds:z.array(z.number()).min(2)}).parse(req.body); const [created]=await db.execute<ResultSetHeader>('INSERT INTO comparison_groups(name,description,created_by) VALUES(?,?,?)',[input.name,input.description||null,req.user!.id]); for(const [order,id] of input.profileIds.entries()) await db.execute('INSERT INTO comparison_group_profiles VALUES(?,?,?)',[created.insertId,id,order]); res.status(201).json({id:created.insertId}); }));
app.get('/api/comparisons/:id', wrap(async(req,res)=>{ const group=await rows<RowDataPacket[]>('SELECT * FROM comparison_groups WHERE id=?',[idOf(req)]);if(!group[0])return res.status(404).json({message:'Grupo não encontrado.'}); const profiles=await rows<RowDataPacket[]>('SELECT p.* FROM comparison_group_profiles gp JOIN instagram_profiles p ON p.id=gp.profile_id WHERE gp.comparison_group_id=? ORDER BY gp.display_order',[idOf(req)]); res.json({group:group[0],profiles}); }));
app.get('/api/comparison-groups', wrap(async(_req,res)=>{ res.json(await rows<RowDataPacket[]>(`SELECT g.*,COUNT(gp.profile_id) profile_count,COALESCE(GROUP_CONCAT(gp.profile_id ORDER BY gp.display_order SEPARATOR ','),'') profile_ids FROM comparison_groups g LEFT JOIN comparison_group_profiles gp ON gp.comparison_group_id=g.id GROUP BY g.id ORDER BY g.created_at DESC`)); }));
const comparisonGroupSchema=z.object({name:z.string().trim().min(2).max(150),description:z.string().trim().max(1000).optional(),profileIds:z.array(z.number().int().positive()).max(10).optional()});
app.post('/api/comparison-groups', wrap(async(req,res)=>{ const input=comparisonGroupSchema.parse(req.body);const profileIds=[...new Set(input.profileIds||[])];const id=await transaction(async c=>{if(profileIds.length){const marks=profileIds.map(()=>'?').join(',');const [found]=await c.execute<RowDataPacket[]>(`SELECT id FROM instagram_profiles WHERE is_active=1 AND id IN (${marks})`,profileIds);if(found.length!==profileIds.length)throw Object.assign(new Error('Um ou mais perfis não estão disponíveis.'),{status:400});}const [result]=await c.execute<ResultSetHeader>('INSERT INTO comparison_groups(name,description,created_by) VALUES(?,?,?)',[input.name,input.description||null,req.user!.id]);for(const [order,profileId] of profileIds.entries())await c.execute('INSERT INTO comparison_group_profiles VALUES(?,?,?)',[result.insertId,profileId,order]);return result.insertId;});res.status(201).json({id}); }));
app.put('/api/comparison-groups/:id', wrap(async(req,res)=>{ const groupId=idOf(req);const input=comparisonGroupSchema.parse(req.body);const profileIds=input.profileIds?[...new Set(input.profileIds)]:undefined;await transaction(async c=>{if(profileIds?.length){const marks=profileIds.map(()=>'?').join(',');const [found]=await c.execute<RowDataPacket[]>(`SELECT id FROM instagram_profiles WHERE is_active=1 AND id IN (${marks})`,profileIds);if(found.length!==profileIds.length)throw Object.assign(new Error('Um ou mais perfis não estão disponíveis.'),{status:400});}const [updated]=await c.execute<ResultSetHeader>('UPDATE comparison_groups SET name=?,description=? WHERE id=?',[input.name,input.description||null,groupId]);if(!updated.affectedRows)throw Object.assign(new Error('Grupo não encontrado.'),{status:404});if(profileIds){await c.execute('DELETE FROM comparison_group_profiles WHERE comparison_group_id=?',[groupId]);for(const [order,profileId] of profileIds.entries())await c.execute('INSERT INTO comparison_group_profiles VALUES(?,?,?)',[groupId,profileId,order]);}});res.status(204).end(); }));
app.delete('/api/comparison-groups/:id', wrap(async(req,res)=>{ await db.execute('DELETE FROM comparison_groups WHERE id=?',[idOf(req)]); res.status(204).end(); }));

function csvCell(value:unknown){ return `"${String(value??'').replaceAll('"','""')}"`; }
app.get('/api/profiles/:id/export.csv', wrap(async(req,res)=>{ const data=await rows<RowDataPacket[]>(`SELECT p.shortcode,p.post_type,p.caption,p.post_url,p.published_at,m.likes_count,m.comments_count,m.views_count,m.plays_count,m.engagement_rate FROM instagram_posts p LEFT JOIN post_metrics m ON m.id=(SELECT id FROM post_metrics WHERE post_id=p.id ORDER BY collected_at DESC LIMIT 1) WHERE p.profile_id=? ORDER BY p.published_at DESC`,[idOf(req)]); const columns=['shortcode','post_type','caption','post_url','published_at','likes_count','comments_count','views_count','plays_count','engagement_rate']; const csv='\uFEFF'+[columns.join(';'),...data.map(row=>columns.map(c=>csvCell(row[c])).join(';'))].join('\n'); res.type('text/csv').attachment('instagram-posts.csv').send(csv); }));
app.post('/api/comparisons/export.csv', wrap(async(req,res)=>{ const ids=z.object({profileIds:z.array(z.number()).min(2)}).parse(req.body).profileIds; const marks=ids.map(()=>'?').join(','); const data=await rows<RowDataPacket[]>(`${dashboardSql.replace('WHERE p.id=?',`WHERE p.id IN (${marks})`)}`,ids); const columns=['username','followers_count','posts_count','average_likes','average_comments','average_engagement','engagement_rate']; const csv='\uFEFF'+[columns.join(';'),...data.map(row=>columns.map(c=>csvCell(row[c])).join(';'))].join('\n'); res.type('text/csv').attachment('comparacao-perfis.csv').send(csv); }));

const dist=resolve('dist'); if(existsSync(dist)){ app.use(express.static(dist)); app.use((req,res,next)=>req.method==='GET'&&!req.path.startsWith('/api/')?res.sendFile(resolve(dist,'index.html')):next()); }
app.use((error:any,_req:Request,res:Response,_next:NextFunction)=>{ if(error instanceof z.ZodError){const issue=error.issues[0];const field=issue?.path?.length?`${issue.path.join('.')}: `:'';return res.status(400).json({message:`${field}${issue?.message||'Dados inválidos.'}`,issues:error.issues});} console.error(error); res.status(error.status||500).json({message:error.status?error.message:'Erro interno do servidor.'}); });

async function bootstrap(){ await initializeDatabase(); app.listen(env.PORT,()=>console.log(`Studek Analytics disponível na porta ${env.PORT}`));void processAiQueue();setInterval(()=>void processAiQueue(),5_000).unref();
  let polling=false; setInterval(async()=>{ if(polling)return; polling=true; try{ const active=await rows<(RowDataPacket&{id:number})[]>('SELECT id FROM apify_runs WHERE status=\'running\' ORDER BY created_at LIMIT 20'); await Promise.allSettled(active.map(run=>refreshLocalRun(run.id))); }finally{polling=false;} },env.COLLECTION_POLL_INTERVAL_SECONDS*1000).unref(); }
bootstrap().catch(error=>{ console.error('Falha ao iniciar:',error); process.exit(1); });
