import {useCallback,useEffect,useState,type FormEvent,type ReactNode} from 'react';
import {Check,KeyRound,LockKeyhole,Mail,Plus,Save,ShieldCheck,Trash2,UserCog,Users,X} from 'lucide-react';
import {api,errorMessage} from '../api';

type Row=Record<string,any>;
const screens=[
  {key:'dashboard',label:'Visão geral',description:'Dashboard estratégico e análise com IA.'},
  {key:'profiles',label:'Perfis monitorados',description:'Cadastro, conteúdo e detalhes dos perfis do Instagram.'},
  {key:'comparisons',label:'Comparações',description:'Benchmark entre o perfil base e concorrentes.'},
  {key:'comparison_groups',label:'Grupos',description:'Criação e edição dos grupos de comparação.'},
  {key:'collections',label:'Coletas',description:'Execução e histórico das coletas de dados.'},
  {key:'settings',label:'Configurações',description:'Configurações de coleta e inteligência artificial.'},
] as const;

function PageTitle({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action:ReactNode}){return <div className="access-page-title"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>}
function Message({type='error',children}:{type?:'error'|'success';children:ReactNode}){return <div className={`access-message ${type}`}>{type==='success'?<Check/>:<ShieldCheck/>}{children}</div>}
function Modal({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:ReactNode}){return <div className="modal-wrap" role="dialog" aria-modal="true"><div className="backdrop" onClick={onClose}/><div className="modal access-modal"><div className="modal-head"><div><span className="eyebrow">CONTROLE DE ACESSO</span><h2>{title}</h2><p>{subtitle}</p></div><button type="button" className="icon-btn" onClick={onClose}><X/></button></div>{children}</div></div>}

const emptyProfile={id:null,name:'',description:'',isActive:true,permissions:[] as string[]};
export function AccessProfilesPage(){
  const [profiles,setProfiles]=useState<Row[]>([]);const [editing,setEditing]=useState<Row|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{setProfiles((await api.get('/access-profiles')).data)}catch(error){setError(errorMessage(error))}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  function toggle(key:string){if(!editing)return;const permissions=editing.permissions.includes(key)?editing.permissions.filter((item:string)=>item!==key):[...editing.permissions,key];setEditing({...editing,permissions})}
  async function save(event:FormEvent){event.preventDefault();if(!editing)return;setSaving(true);setError('');try{const payload={name:editing.name,description:editing.description||null,isActive:Boolean(editing.isActive),permissions:editing.permissions};if(editing.id)await api.put(`/access-profiles/${editing.id}`,payload);else await api.post('/access-profiles',payload);setEditing(null);setSuccess('Perfil de acesso salvo com sucesso.');await load()}catch(error){setError(errorMessage(error))}finally{setSaving(false)}}
  async function remove(profile:Row){if(!window.confirm(`Excluir o perfil de acesso “${profile.name}”?`))return;setError('');try{await api.delete(`/access-profiles/${profile.id}`);setSuccess('Perfil de acesso excluído.');await load()}catch(error){setError(errorMessage(error))}}
  return <div className="access-page"><PageTitle eyebrow="PERMISSÕES" title="Perfis de acesso" description="Defina quais áreas do sistema cada tipo de usuário poderá acessar." action={<button className="button primary" onClick={()=>setEditing({...emptyProfile,permissions:[]})}><Plus/>Novo perfil</button>}/>{error&&<Message>{error}</Message>}{success&&<Message type="success">{success}</Message>}{loading?<div className="loader"><span/><span/><span/></div>:profiles.length?<div className="access-profile-grid">{profiles.map(profile=><article key={profile.id} className={!profile.is_active?'inactive':''}><div className="access-card-head"><div className="access-card-icon"><LockKeyhole/></div><span className={profile.is_active?'access-status active':'access-status'}>{profile.is_active?'Ativo':'Inativo'}</span></div><h2>{profile.name}</h2><p>{profile.description||'Sem descrição.'}</p><div className="access-card-count"><b>{profile.permissions.length}</b><span>de {screens.length} telas liberadas</span></div><div className="access-card-tags">{profile.permissions.length?profile.permissions.map((permission:string)=><span key={permission}>{screens.find(screen=>screen.key===permission)?.label||permission}</span>):<small>Nenhuma tela liberada</small>}</div><div className="access-card-foot"><span><Users/> {profile.user_count} usuário{profile.user_count===1?'':'s'}</span><div><button className="button ghost" onClick={()=>setEditing({...profile,isActive:Boolean(profile.is_active),permissions:[...profile.permissions]})}>Editar</button><button className="icon-btn danger" disabled={profile.user_count>0} onClick={()=>remove(profile)} title={profile.user_count?'Existem usuários associados':'Excluir perfil'}><Trash2/></button></div></div></article>)}</div>:<div className="access-empty"><LockKeyhole/><h2>Nenhum perfil de acesso</h2><p>Crie o primeiro perfil e selecione as telas que ele poderá acessar.</p><button className="button primary" onClick={()=>setEditing({...emptyProfile,permissions:[]})}><Plus/>Criar perfil</button></div>}
  {editing&&<Modal title={editing.id?'Editar perfil de acesso':'Novo perfil de acesso'} subtitle="Escolha um nome e marque as telas que ficarão disponíveis." onClose={()=>!saving&&setEditing(null)}><form onSubmit={save}><div className="access-form-row"><label>Nome<input autoFocus value={editing.name} onChange={event=>setEditing({...editing,name:event.target.value})} placeholder="Ex.: Analista de marketing"/></label><label className="access-active-field">Situação<select value={editing.isActive?'active':'inactive'} onChange={event=>setEditing({...editing,isActive:event.target.value==='active'})}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label></div><label>Descrição<textarea rows={2} value={editing.description||''} onChange={event=>setEditing({...editing,description:event.target.value})} placeholder="Responsabilidades deste perfil"/></label><div className="permission-editor"><div><b>Telas permitidas</b><span>{editing.permissions.length} selecionadas</span></div>{screens.map(screen=>{const checked=editing.permissions.includes(screen.key);return <button type="button" className={checked?'selected':''} key={screen.key} onClick={()=>toggle(screen.key)}><i>{checked&&<Check/>}</i><span><b>{screen.label}</b><small>{screen.description}</small></span></button>})}</div><div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setEditing(null)}>Cancelar</button><button className="button primary" disabled={saving||!editing.name.trim()}><Save/>{saving?'Salvando…':'Salvar perfil'}</button></div></form></Modal>}</div>
}

const emptyUser={id:null,name:'',email:'',password:'',role:'user',accessProfileId:'',isActive:true};
export function SystemUsersPage(){
  const [users,setUsers]=useState<Row[]>([]);const [profiles,setProfiles]=useState<Row[]>([]);const [editing,setEditing]=useState<Row|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
  const current=JSON.parse(localStorage.getItem('studek_user')||'{}');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [userResponse,profileResponse]=await Promise.all([api.get('/system-users'),api.get('/access-profiles')]);setUsers(userResponse.data);setProfiles(profileResponse.data.filter((profile:Row)=>profile.is_active))}catch(error){setError(errorMessage(error))}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  function edit(user:Row){setEditing({id:user.id,name:user.name,email:user.email,password:'',role:user.role,accessProfileId:user.access_profile_id||'',isActive:Boolean(user.is_active)})}
  async function save(event:FormEvent){event.preventDefault();if(!editing)return;setSaving(true);setError('');try{const payload={name:editing.name,email:editing.email,password:editing.password||undefined,role:editing.role,accessProfileId:editing.role==='admin'?null:Number(editing.accessProfileId)||null,isActive:Boolean(editing.isActive)};if(editing.id)await api.put(`/system-users/${editing.id}`,payload);else await api.post('/system-users',payload);setEditing(null);setSuccess('Usuário salvo com sucesso.');await load()}catch(error){setError(errorMessage(error))}finally{setSaving(false)}}
  async function remove(user:Row){if(!window.confirm(`Excluir o usuário “${user.name}”?`))return;setError('');try{await api.delete(`/system-users/${user.id}`);setSuccess('Usuário excluído.');await load()}catch(error){setError(errorMessage(error))}}
  return <div className="access-page"><PageTitle eyebrow="ADMINISTRAÇÃO" title="Usuários do sistema" description="Cadastre usuários e associe cada pessoa a um perfil de acesso." action={<button className="button primary" onClick={()=>setEditing({...emptyUser})}><Plus/>Novo usuário</button>}/>{error&&<Message>{error}</Message>}{success&&<Message type="success">{success}</Message>}{loading?<div className="loader"><span/><span/><span/></div>:<section className="panel system-users-panel"><div className="system-users-summary"><div><Users/><span><b>{users.length}</b> usuários cadastrados</span></div><div><ShieldCheck/><span><b>{users.filter(user=>user.is_active).length}</b> acessos ativos</span></div></div><div className="system-users-table"><table><thead><tr><th>Usuário</th><th>Perfil de acesso</th><th>Tipo</th><th>Status</th><th>Última alteração</th><th/></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><div className="system-user-cell"><span>{String(user.name||'?')[0].toUpperCase()}</span><div><b>{user.name}</b><small>{user.email}</small></div></div></td><td>{user.role==='admin'?<span className="admin-access"><ShieldCheck/>Acesso total</span>:user.access_profile_name||<em>Sem perfil</em>}</td><td>{user.role==='admin'?'Administrador':'Usuário'}</td><td><span className={user.is_active?'access-status active':'access-status'}>{user.is_active?'Ativo':'Inativo'}</span></td><td>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(user.updated_at))}</td><td><div className="row-actions"><button className="button ghost" onClick={()=>edit(user)}>Editar</button><button className="icon-btn danger" disabled={Number(user.id)===Number(current.id)} onClick={()=>remove(user)}><Trash2/></button></div></td></tr>)}</tbody></table></div></section>}
  {editing&&<Modal title={editing.id?'Editar usuário':'Novo usuário'} subtitle="Informe os dados de acesso e associe um perfil de permissões." onClose={()=>!saving&&setEditing(null)}><form onSubmit={save}><div className="access-form-row"><label>Nome<input autoFocus value={editing.name} onChange={event=>setEditing({...editing,name:event.target.value})} placeholder="Nome completo"/></label><label>E-mail<div className="input-with-icon"><Mail/><input type="email" value={editing.email} onChange={event=>setEditing({...editing,email:event.target.value})} placeholder="usuario@empresa.com"/></div></label></div><div className="access-form-row"><label>Tipo de usuário<select value={editing.role} onChange={event=>setEditing({...editing,role:event.target.value,accessProfileId:event.target.value==='admin'?'':editing.accessProfileId})}><option value="user">Usuário</option><option value="admin">Administrador</option></select></label><label>Perfil de acesso<select value={editing.accessProfileId} disabled={editing.role==='admin'} onChange={event=>setEditing({...editing,accessProfileId:event.target.value})}><option value="">Selecione um perfil</option>{profiles.map(profile=><option value={profile.id} key={profile.id}>{profile.name}</option>)}</select></label></div><div className="access-form-row"><label>{editing.id?'Nova senha (opcional)':'Senha'}<div className="input-with-icon"><KeyRound/><input type="password" minLength={8} required={!editing.id} value={editing.password} onChange={event=>setEditing({...editing,password:event.target.value})} placeholder={editing.id?'Manter senha atual':'Mínimo de 8 caracteres'}/></div></label><label>Situação<select value={editing.isActive?'active':'inactive'} disabled={Number(editing.id)===Number(current.id)} onChange={event=>setEditing({...editing,isActive:event.target.value==='active'})}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label></div>{editing.role==='admin'&&<div className="admin-warning"><UserCog/><span><b>Administrador</b> terá acesso irrestrito a todas as telas e à gestão de usuários.</span></div>}<div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setEditing(null)}>Cancelar</button><button className="button primary" disabled={saving||!editing.name.trim()||!editing.email.trim()||(editing.role==='user'&&!editing.accessProfileId)}><Save/>{saving?'Salvando…':'Salvar usuário'}</button></div></form></Modal>}</div>
}
