import {useCallback,useEffect,useMemo,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Activity,ArrowUpRight,CalendarDays,Check,Crown,Eye,Heart,Images,MessageCircle,Play,Printer,RefreshCw,Search,SlidersHorizontal,Star,TrendingUp,Trophy,Users,Video} from 'lucide-react';
import {api,errorMessage} from '../api';
import {exportElementToLandscapePdf} from '../utils/exportPdf';
type Row=Record<string,any>;
const colors=['#7557ef','#2bb18c','#f1a33a','#e45b79','#4d99d4','#9b6ac6'];
const compact=(v:any)=>new Intl.NumberFormat('pt-BR',{notation:Number(v)>9999?'compact':'standard',maximumFractionDigits:1}).format(Number(v)||0);
const pct=(v:any)=>`${Number(v||0).toFixed(2).replace('.',',')}%`;
const dateLabel=(v:string)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(`${v}T12:00:00`));
const fullDate=(v:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'full'}).format(new Date(`${v}T12:00:00`));
const mixWithWhite=(hex:string,amount:number)=>{const color=hex.replace('#','');const ratio=Math.max(0,Math.min(100,amount))/100;const channels=[0,2,4].map(offset=>Math.round(255-(255-parseInt(color.slice(offset,offset+2),16))*ratio));return `rgb(${channels.join(', ')})`};
const metrics:Record<string,string>={engagement:'Engajamento',posts:'Publicações',likes:'Curtidas',comments:'Comentários',plays:'Reproduções',views:'Visualizações',reels:'Reels',stories:'Stories'};
function Avatar({profile}:{profile:Row}){return <div className="compare-avatar">{String(profile.username||'?')[0].toUpperCase()}{profile.profile_picture_url&&<img src={`/api/media/profiles/${profile.id}/picture`} alt={`@${profile.username}`} onError={event=>{event.currentTarget.style.display='none'}}/>}</div>}
function Loading(){return <div className="compare-loading"><span/><span/><span/>Comparando dados dos perfis…</div>}
export default function ComparisonDashboard(){
  const [searchParams]=useSearchParams();
  const [data,setData]=useState<Row|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selected,setSelected]=useState<number[]>([]);const [period,setPeriod]=useState('month');const [custom,setCustom]=useState({from:'',to:''});const [metric,setMetric]=useState('engagement');const [focusDate,setFocusDate]=useState('');const [pdfExporting,setPdfExporting]=useState(false);
  const load=useCallback(async(options?:{ids?:number[];period?:string;from?:string;to?:string})=>{setLoading(true);setError('');try{const ids=options?.ids||selected;const chosenPeriod=options?.period||period;const response=await api.get('/comparisons/dashboard',{params:{profileIds:ids.length?ids.join(','):undefined,period:chosenPeriod,from:options?.from,to:options?.to}});setData(response.data);setSelected(response.data.selectedProfiles.map((p:Row)=>Number(p.id)));if(!focusDate)setFocusDate(String(response.data.period.to).slice(0,10))}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[selected,period,focusDate]);
  useEffect(()=>{const ids=String(searchParams.get('profileIds')||'').split(',').map(Number).filter(Number.isInteger);load({ids,period:'month'})},[]);
  async function choosePeriod(value:string){setPeriod(value);if(value!=='custom')await load({ids:selected,period:value})}
  async function applyCustom(){if(custom.from&&custom.to)await load({ids:selected,period:'custom',...custom})}
  async function toggleProfile(id:number){if(Number(data?.baseProfileId)===id)return;const next=selected.includes(id)?selected.filter(x=>x!==id):[...selected,id];if(next.length<2||next.length>6)return;setSelected(next);await load({ids:next,period,from:period==='custom'?custom.from:undefined,to:period==='custom'?custom.to:undefined})}
  const chart=useMemo(()=>{if(!data)return[];const map=new Map<string,Row>();for(const row of data.daily){const item=map.get(row.date)||{date:row.date,label:dateLabel(row.date)};item[row.username]=Number(row[metric]||0);map.set(row.date,item)}return [...map.values()]},[data,metric]);
  const formatChart=useMemo(()=>{if(!data)return[];const map=new Map<string,Row>();for(const row of data.formats){const item=map.get(row.format)||{format:row.format};item[row.username]=Number(row.averageEngagement||0);map.set(row.format,item)}return [...map.values()]},[data]);
  const activePosts=useMemo(()=>data?.posts?.filter((p:Row)=>String(p.published_at).slice(0,10)===focusDate)||[],[data,focusDate]);
  const maxDay=Math.max(1,...(data?.weekdays||[]).map((r:Row)=>Number(r.averageEngagement)));
  async function exportPdf(){setPdfExporting(true);setError('');try{await exportElementToLandscapePdf('.compare-dashboard','perfil-base-concorrentes.pdf')}catch(e){setError(errorMessage(e))}finally{setPdfExporting(false)}}
  if(loading&&!data)return <Loading/>;
  return <div className="compare-dashboard">
    <div className="compare-head"><div><span><TrendingUp/> BENCHMARK AVANÇADO</span><h1>Perfil base × concorrentes</h1><p>Compare estratégia, frequência e desempenho de conteúdo em qualquer período.</p></div><div className="compare-head-actions"><div className="period-tabs"><button className={period==='day'?'active':''} onClick={()=>choosePeriod('day')}>Hoje</button><button className={period==='week'?'active':''} onClick={()=>choosePeriod('week')}>7 dias</button><button className={period==='month'?'active':''} onClick={()=>choosePeriod('month')}>30 dias</button><button className={period==='custom'?'active':''} onClick={()=>setPeriod('custom')}>Personalizado</button></div><button data-pdf-ignore className="dashboard-print" onClick={exportPdf} disabled={pdfExporting}><Printer/>{pdfExporting?'Gerando PDF…':'Baixar PDF'}</button></div></div>
    <section className="compare-filters"><div className="profile-selector"><span>Perfis comparados</span><div>{data?.profiles?.map((profile:Row)=>{const checked=selected.includes(Number(profile.id)),base=Number(data.baseProfileId)===Number(profile.id);return <button key={profile.id} className={checked?'selected':''} onClick={()=>toggleProfile(Number(profile.id))}><Avatar profile={profile}/><b>@{profile.username}</b>{base?<em><Crown/> Base</em>:checked?<Check/>:null}</button>})}</div></div>{period==='custom'&&<div className="custom-period"><label>De<input type="date" value={custom.from} onChange={e=>setCustom({...custom,from:e.target.value})}/></label><label>Até<input type="date" value={custom.to} onChange={e=>setCustom({...custom,to:e.target.value})}/></label><button onClick={applyCustom}><SlidersHorizontal/>Aplicar período</button></div>}<button className="compare-refresh" onClick={()=>load({ids:selected,period,from:custom.from,to:custom.to})}><RefreshCw/>Atualizar</button></section>
    {error&&<div className="compare-error"><Activity/>{error}</div>}
    {data&&<>
      <div className="compare-summary-grid">{data.summaries.map((profile:Row,index:number)=><article key={profile.id} style={{'--profile-color':colors[index]} as any}><div className="summary-profile"><Avatar profile={profile}/><div><b>@{profile.username}</b><span>{Number(data.baseProfileId)===Number(profile.id)?<><Crown/> Perfil base</>:'Concorrente'}</span></div></div><strong>{compact(profile.followers_count)}</strong><small>seguidores</small><div className="summary-stats"><div><span>Engajamento</span><b>{pct(profile.engagementRate)}</b></div><div><span>Publicações</span><b>{profile.posts}</b></div><div><span>Média / semana</span><b>{Number(profile.publicationsPerWeek).toFixed(1).replace('.',',')}</b></div><div><span>Melhor formato</span><b>{profile.bestFormat||'—'}</b></div><div><span>Melhor dia</span><b>{profile.bestDay||'—'}</b></div><div><span>Eng. médio</span><b>{compact(profile.averageEngagement)}</b></div></div><div className="surface-counts"><span><Video/> {profile.reels} Reels</span><span><Eye/> {profile.stories} Stories</span><span><Images/> {profile.feed} Feed</span></div><Link className="summary-dashboard-link" to={`/profiles/${profile.id}?view=comparison`}>Dashboard de conteúdo <ArrowUpRight/></Link></article>)}</div>
      <div className="compare-main-grid"><section className="compare-panel daily-chart"><div className="compare-panel-head"><div><span>LINHA DO TEMPO</span><h2>Desempenho diário</h2><p>Clique em um dia no gráfico para ver o que cada perfil publicou.</p></div><select value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(metrics).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div><ResponsiveContainer width="100%" height={340}><LineChart data={chart} onClick={(state:any)=>state?.activeLabel&&setFocusDate(state.activeLabel)} margin={{left:-10,right:15,top:10}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={dateLabel} minTickGap={22}/><YAxis tickFormatter={compact}/><Tooltip labelFormatter={v=>fullDate(String(v))} formatter={(v:any)=>compact(v)}/><Legend/>{data.summaries.map((p:Row,i:number)=><Line key={p.id} type="monotone" dataKey={p.username} name={`@${p.username}`} stroke={colors[i]} strokeWidth={3} dot={{r:2}} activeDot={{r:6}} connectNulls/>)}</LineChart></ResponsiveContainer></section><section className="compare-panel day-detail"><div className="compare-panel-head"><div><span>DETALHE DO DIA</span><h2>{focusDate?fullDate(focusDate):'Selecione uma data'}</h2><p>{activePosts.length} conteúdos publicados</p></div><input type="date" value={focusDate} min={String(data.period.from).slice(0,10)} max={String(data.period.to).slice(0,10)} onChange={e=>setFocusDate(e.target.value)}/></div>{activePosts.length?<div className="day-posts">{activePosts.map((post:Row)=><Link key={post.id} to={`/posts/${post.id}`}><div className="day-thumb">{post.display_url?<img src={post.display_url} alt=""/>:<Images/>}</div><div><span>@{post.username} · {post.format}</span><b>{post.caption||'Conteúdo sem legenda'}</b><small><Heart/>{compact(post.likes_count)} <MessageCircle/>{compact(post.comments_count)} <Play/>{compact(post.plays_count)}</small></div><ArrowUpRight/></Link>)}</div>:<div className="day-empty"><CalendarDays/><b>Nenhuma publicação neste dia</b><span>Escolha outro ponto da linha do tempo.</span></div>}</section></div>
      <div className="compare-analysis-grid"><section className="compare-panel"><div className="compare-panel-head"><div><span>FORMATOS</span><h2>Engajamento médio por formato</h2><p>Identifique Reels, Stories e formatos de Feed mais eficientes.</p></div></div><ResponsiveContainer width="100%" height={285}><BarChart data={formatChart} margin={{left:-15,right:10}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="format"/><YAxis tickFormatter={compact}/><Tooltip formatter={(v:any)=>compact(v)}/><Legend/>{data.summaries.map((p:Row,i:number)=><Bar key={p.id} dataKey={p.username} name={`@${p.username}`} fill={colors[i]} radius={[5,5,0,0]} maxBarSize={32}/>)}</BarChart></ResponsiveContainer></section><section className="compare-panel weekday-panel"><div className="compare-panel-head"><div><span>DIAS DA SEMANA</span><h2>Quando o público mais engaja</h2><p>Engajamento médio por dia e perfil.</p></div></div><div className="weekday-matrix"><div className="weekday-row header"><span>Perfil</span>{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(day=><b key={day}>{day}</b>)}</div>{data.summaries.map((profile:Row,i:number)=><div className="weekday-row" key={profile.id}><span><i style={{background:colors[i]}}/>@{profile.username}</span>{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(day=>{const row=data.weekdays.find((r:Row)=>r.profileId===Number(profile.id)&&r.weekday===day);const value=Number(row?.averageEngagement||0);return <b key={day} title={`${compact(value)} engajamentos em média`} style={{backgroundColor:mixWithWhite(colors[i],Math.max(5,value/maxDay*85))}}>{value?compact(value):'—'}</b>})}</div>)}</div></section></div>
      <section className="compare-panel activity-table"><div className="compare-panel-head"><div><span>CALENDÁRIO DE CONTEÚDO</span><h2>O que cada perfil fez por dia</h2><p>Volume, formato e resultado diário no período selecionado.</p></div></div><div className="compare-table-wrap"><table><thead><tr><th>Data</th><th>Perfil</th><th>Publicações</th><th>Reels</th><th>Stories</th><th>Engajamento</th><th>Curtidas</th><th>Comentários</th><th>Reproduções</th><th>Visualizações</th></tr></thead><tbody>{data.daily.filter((d:Row)=>d.posts>0).sort((a:Row,b:Row)=>b.date.localeCompare(a.date)).map((row:Row)=><tr key={`${row.profileId}-${row.date}`} onClick={()=>setFocusDate(row.date)}><td><b>{dateLabel(row.date)}</b></td><td>@{row.username}</td><td>{row.posts}</td><td>{row.reels}</td><td>{row.stories}</td><td><strong>{compact(row.engagement)}</strong></td><td>{compact(row.likes)}</td><td>{compact(row.comments)}</td><td>{compact(row.plays)}</td><td>{compact(row.views)}</td></tr>)}</tbody></table></div></section>
      <section className="compare-panel compare-top10"><div className="compare-panel-head"><div><span>RANKING GERAL</span><h2>Top 10 publicações dos perfis</h2><p>Ordenadas pelo engajamento total no período. Clique para acompanhar o desempenho completo.</p></div></div><div className="top10-list">{data.top10?.map((post:Row)=><Link key={post.id} to={`/posts/${post.id}`}><strong>{post.position}</strong><div className="top10-thumb">{post.display_url?<img src={post.display_url} alt=""/>:<Images/>}</div><div className="top10-copy"><span>@{post.username} · {post.format}</span><b>{post.caption||'Conteúdo sem legenda'}</b><small><Heart/>{compact(post.likes_count)} <MessageCircle/>{compact(post.comments_count)} <Trophy/>{compact(post.engagement_count)} <Play/>{compact(post.plays_count)}</small></div><ArrowUpRight/></Link>)}</div></section>
      <section className="compare-panel top-by-profile"><div className="compare-panel-head"><div><span>CONTEÚDOS LÍDERES</span><h2>Maior engajamento por perfil</h2><p>Publicações que mais contribuíram para o resultado no período.</p></div></div><div className="top-columns">{data.summaries.map((profile:Row,i:number)=><div key={profile.id}><h3><i style={{background:colors[i]}}/>@{profile.username}</h3>{data.topPosts.filter((p:Row)=>Number(p.profile_id)===Number(profile.id)).map((post:Row,index:number)=><Link key={post.id} to={`/posts/${post.id}`}><span>{index+1}</span><div>{post.display_url?<img src={post.display_url} alt=""/>:<Images/>}</div><p><b>{post.caption||'Conteúdo sem legenda'}</b><small>{post.format} · {compact(post.engagement_count)} engajamentos</small></p><ArrowUpRight/></Link>)}</div>)}</div></section>
    </>}
  </div>
}
