import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {ArrowRight,BarChart3,BrainCircuit,CalendarDays,Camera,Check,ChevronDown,CircleAlert,Crown,Flag,Hash,Heart,Lightbulb,Megaphone,Printer,RefreshCw,Rocket,Settings,Sparkles,Star,Target,TrendingUp,Users,Zap} from 'lucide-react';
import {api,errorMessage} from '../api';
import {exportElementToLandscapePdf} from '../utils/exportPdf';
type Row=Record<string,any>;
const colors=['#7657ef','#26a781','#f0a33c','#e55d7b','#4e9bd7'];
const compact=(value:any)=>new Intl.NumberFormat('pt-BR',{notation:Number(value)>9999?'compact':'standard',maximumFractionDigits:1}).format(Number(value)||0);
const pct=(value:any)=>`${Number(value||0).toFixed(2).replace('.',',')}%`;
const signed=(value:any)=>`${Number(value)>=0?'+':''}${compact(value)}`;
function Loading(){return <div className="strategy-loading"><span/><span/><span/>Construindo leitura estratégica…</div>}
function Avatar({profile,size='normal'}:{profile:Row;size?:string}){return <div className={`strategy-avatar ${size}`}>{String(profile.username||'?')[0].toUpperCase()}{profile.profile_picture_url&&<img src={`/api/media/profiles/${profile.id}/picture`} alt={`@${profile.username}`} onError={event=>{event.currentTarget.style.display='none'}}/>}</div>}
export default function StrategyDashboard(){
  const navigate=useNavigate();const [data,setData]=useState<Row|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selectedId,setSelectedId]=useState<number>();const [savingBase,setSavingBase]=useState(false);const [profileMenuOpen,setProfileMenuOpen]=useState(false);const [ai,setAi]=useState<Row|null>(null);const [aiLoading,setAiLoading]=useState(true);const [aiGenerating,setAiGenerating]=useState(false);const [pdfExporting,setPdfExporting]=useState(false);const [aiError,setAiError]=useState('');const profileMenuRef=useRef<HTMLDivElement>(null);
  const load=useCallback(async(id?:number)=>{setLoading(true);setError('');try{const response=await api.get('/dashboard/strategy',{params:id?{profileId:id}:{}});setData(response.data);if(response.data.selected)setSelectedId(Number(response.data.selected.id))}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  const loadAi=useCallback(async(silent=false)=>{if(!silent)setAiLoading(true);try{const payload=(await api.get('/ai/analysis/base')).data;setAi(payload);setAiError(payload.job?.status==='failed'?(payload.job.errorMessage||'A análise não pôde ser concluída.'):'')}catch(e){setAiError(errorMessage(e))}finally{if(!silent)setAiLoading(false)}},[]);useEffect(()=>{loadAi()},[loadAi]);
  const aiJobStatus=ai?.job?.status;useEffect(()=>{if(aiJobStatus!=='queued'&&aiJobStatus!=='running')return;const timer=window.setInterval(()=>void loadAi(true),3_000);return()=>window.clearInterval(timer)},[aiJobStatus,loadAi]);
  useEffect(()=>{if(!profileMenuOpen)return;const close=(event:PointerEvent)=>{if(!profileMenuRef.current?.contains(event.target as Node))setProfileMenuOpen(false)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[profileMenuOpen]);
  async function selectProfile(id:number){setSelectedId(id);await load(id)}
  async function setBase(){if(!selectedId)return;setSavingBase(true);try{await api.post(`/profiles/${selectedId}/set-base`);await Promise.all([load(selectedId),loadAi()])}catch(e){setError(errorMessage(e))}finally{setSavingBase(false)}}
  async function generateAi(){setAiGenerating(true);setAiError('');try{const response=await api.post('/ai/analyze-base');setAi((current:Row|null)=>({...current,job:response.data.job}));}catch(e){setAiError(errorMessage(e))}finally{setAiGenerating(false)}}
  async function printAi(){setPdfExporting(true);setAiError('');try{const username=data?.profiles?.find((item:Row)=>Number(item.id)===Number(data.baseProfileId))?.username||'perfil-base';await exportElementToLandscapePdf('.ai-analysis-panel',`analise-ia-${username}.pdf`)}catch(e){setAiError(errorMessage(e))}finally{setPdfExporting(false)}}
  const scoreChart=useMemo(()=>{if(!data?.scores)return[];const shown=data.scores.filter((p:Row)=>Number(p.id)===Number(data.selected?.id)||data.competitors.slice(0,3).some((c:Row)=>Number(c.id)===Number(p.id)));return ['Audiência','Engajamento','Frequência','Curtidas','Crescimento'].map(metric=>{const row:Row={metric};for(const profile of shown)row[profile.username]=Math.round(profile.values.find((v:Row)=>v.metric===metric)?.score||0);return row})},[data]);
  if(loading)return <Loading/>;
  if(error&&!data)return <div className="strategy-error"><CircleAlert/><div><b>Não foi possível abrir a visão estratégica</b><span>{error}</span></div><button onClick={()=>load()}><RefreshCw/>Tentar novamente</button></div>;
  if(!data?.selected)return <div className="strategy-empty"><Camera/><h1>Cadastre o primeiro perfil</h1><p>O painel estratégico precisa de ao menos um perfil monitorado.</p><button onClick={()=>navigate('/profiles')}>Adicionar perfil</button></div>;
  const profile=data.selected;const isBase=Number(data.baseProfileId)===Number(profile.id);
  return <div className="strategy-dashboard">
    <div className="strategy-top"><div><span className="strategy-eyebrow"><Target/> VISÃO ESTRATÉGICA</span><h1>Desempenho individual</h1><p>Use seu perfil como referência e transforme diferenças competitivas em ações.</p></div><div className="strategy-controls"><div className="strategy-profile-control" ref={profileMenuRef}><span>Perfil analisado</span><button type="button" className={`strategy-select-trigger ${profileMenuOpen?'open':''}`} aria-haspopup="listbox" aria-expanded={profileMenuOpen} onClick={()=>setProfileMenuOpen(open=>!open)} onKeyDown={event=>{if(event.key==='Escape')setProfileMenuOpen(false);if(event.key==='ArrowDown'){event.preventDefault();setProfileMenuOpen(true)}}}><Avatar profile={profile}/><span><b>@{profile.username}</b><small>{isBase?'Perfil base':'Concorrente monitorado'}</small></span><ChevronDown/></button>{profileMenuOpen&&<div className="strategy-select-menu" role="listbox" aria-label="Perfil analisado">{data.profiles.map((item:Row)=>{const selected=Number(item.id)===Number(selectedId);return <button type="button" role="option" aria-selected={selected} className={selected?'selected':''} key={item.id} onClick={()=>{setProfileMenuOpen(false);selectProfile(Number(item.id))}}><Avatar profile={item}/><span><b>@{item.username}</b><small>{Number(data.baseProfileId)===Number(item.id)?'Perfil base':'Concorrente monitorado'}</small></span>{selected&&<Check/>}</button>})}</div>}</div><button className={isBase?'base-button active':'base-button'} onClick={setBase} disabled={isBase||savingBase}>{isBase?<><Crown/>Perfil base</>:savingBase?<><RefreshCw/>Salvando…</>:<><Star/>Definir como perfil base</>}</button></div></div>
    {error&&<div className="strategy-inline-error">{error}</div>}
    <section className="strategy-hero"><div className="strategy-profile"><Avatar profile={profile} size="large"/><div><div className="strategy-title-line"><h2>{profile.full_name||profile.internal_name||`@${profile.username}`}</h2>{isBase&&<span><Crown/> Perfil base</span>}</div><p>@{profile.username} · {profile.last_collected_at?'Dados atualizados':'Aguardando primeira coleta'}</p><button onClick={()=>navigate(`/profiles/${profile.id}`)}>Abrir análise de conteúdo <ArrowRight/></button></div></div><div className="strategy-context"><span>Referência da análise</span><b>{isBase?'Este é o perfil que você quer melhorar':'Visualização individual de concorrente'}</b><small>{isBase?'As recomendações abaixo comparam este perfil com todos os concorrentes monitorados.':'Defina este perfil como base para direcionar o plano de ação a ele.'}</small></div></section>
    <div className="strategy-kpis"><article><div className="strategy-kpi-icon purple"><Users/></div><span>Seguidores</span><strong>{compact(profile.followers_count)}</strong><small className={profile.growth>=0?'up':'down'}><TrendingUp/>{signed(profile.growth)} no histórico</small></article><article><div className="strategy-kpi-icon pink"><Heart/></div><span>Taxa de engajamento</span><strong>{pct(profile.engagement_rate)}</strong><small>{compact(profile.average_engagement)} interações por post</small></article><article><div className="strategy-kpi-icon green"><Zap/></div><span>Publicações em 30 dias</span><strong>{compact(profile.recent_posts)}</strong><small>Cadência recente do perfil</small></article><article><div className="strategy-kpi-icon orange"><BarChart3/></div><span>Média de curtidas</span><strong>{compact(profile.average_likes)}</strong><small>{compact(profile.average_comments)} comentários em média</small></article><article><div className="strategy-kpi-icon blue"><Rocket/></div><span>Melhor formato</span><strong className="format-value">{profile.best_format||'—'}</strong><small>{compact(profile.best_format_engagement)} engajamentos em média</small></article></div>
    <div className="strategy-grid"><section className="strategy-panel comparison-panel"><div className="strategy-panel-head"><div><span>POSICIONAMENTO</span><h2>Índice competitivo</h2><p>Cada indicador é normalizado em relação ao melhor perfil do grupo.</p></div><span className="base-legend"><i/> @{profile.username}</span></div><ResponsiveContainer width="100%" height={310}><BarChart data={scoreChart} margin={{top:12,right:12,left:-20,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="metric"/><YAxis domain={[0,100]} tickFormatter={v=>`${v}%`}/><Tooltip formatter={(v:any)=>`${v}%`}/><Legend/>{[profile,...data.competitors.slice(0,3)].map((p:Row,i:number)=><Bar key={p.id} dataKey={p.username} name={`@${p.username}`} fill={colors[i]} radius={[5,5,0,0]} maxBarSize={28}/>)}</BarChart></ResponsiveContainer></section><section className="strategy-panel rivals-panel"><div className="strategy-panel-head"><div><span>CONCORRENTES</span><h2>Comparação rápida</h2><p>Diferença em relação ao perfil selecionado.</p></div></div>{data.competitors.length?<div className="rivals-list">{data.competitors.map((competitor:Row)=><button key={competitor.id} onClick={()=>selectProfile(Number(competitor.id))}><Avatar profile={competitor}/><div><b>@{competitor.username}</b><span>{compact(competitor.followers_count)} seguidores</span></div><dl><div><dt>Engajamento</dt><dd className={Number(competitor.engagement_rate)>Number(profile.engagement_rate)?'ahead':''}>{pct(competitor.engagement_rate)}</dd></div><div><dt>30 dias</dt><dd>{competitor.recent_posts} posts</dd></div></dl><ArrowRight/></button>)}</div>:<div className="no-rivals"><Users/><b>Nenhum concorrente cadastrado</b><span>Adicione outros perfis para gerar comparações e recomendações.</span><button onClick={()=>navigate('/profiles')}>Adicionar concorrente</button></div>}</section></div>
    <section className="strategy-panel action-panel"><div className="strategy-panel-head"><div><span>PLANO DE AÇÃO</span><h2>Oportunidades para melhorar o desempenho</h2><p>Recomendações calculadas a partir do perfil selecionado e dos concorrentes monitorados.</p></div><span className="action-count"><Lightbulb/>{data.recommendations.length} recomendações</span></div>{data.recommendations.length?<div className="action-list">{data.recommendations.map((item:Row,index:number)=><article className={`action-card ${item.priority}`} key={`${item.category}-${index}`}><div className="action-number">{String(index+1).padStart(2,'0')}</div><div className="action-copy"><span>{item.category}</span><h3>{item.title}</h3><p>{item.insight}</p></div><div className="action-next"><Flag/><div><span>Próxima ação</span><b>{item.action}</b></div></div></article>)}</div>:<div className="no-actions"><Check/><b>Adicione concorrentes para gerar recomendações</b></div>}</section>
    <section className="strategy-panel ai-analysis-panel"><div className="strategy-panel-head"><div><span><Sparkles/> ESTRATÉGIA COM IA</span><h2>Análise do perfil base</h2><p>Diagnóstico baseado nos dados coletados, nos conteúdos líderes e nos concorrentes monitorados.</p></div>{ai?.analysis&&aiJobStatus!=='queued'&&aiJobStatus!=='running'&&<div className="ai-analysis-head-actions"><div className="ai-analysis-meta"><b>{ai.analysis.provider==='openai'?'OpenAI':'Claude'}</b><span>{ai.analysis.model} · {new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(ai.analysis.createdAt))}</span></div><button data-pdf-ignore className="dashboard-print ai-print-button" onClick={printAi} disabled={pdfExporting}><Printer/>{pdfExporting?'Gerando PDF…':'Baixar PDF'}</button></div>}</div>
      {aiLoading?<div className="ai-analysis-loading"><RefreshCw/>Carregando a última análise…</div>:aiJobStatus==='queued'||aiJobStatus==='running'?<div className="ai-analysis-background"><div className="ai-background-spinner"><RefreshCw/></div><div><b>{aiJobStatus==='queued'?'Análise na fila':'Análise sendo gerada em segundo plano'}</b><span>Você pode navegar por outras telas. O resultado aparecerá automaticamente aqui quando estiver pronto.</span><small>{aiJobStatus==='queued'?'Preparando os dados do perfil base…':'Comparando conteúdos, formatos, hashtags, datas e concorrentes…'} A geração pode levar até 3 minutos.</small></div><span className="ai-background-status"><i/> {aiJobStatus==='queued'?'Na fila':'Processando'}</span></div>:aiError?<div className="ai-analysis-empty error"><CircleAlert/><div><b>A análise não pôde ser concluída</b><span>{aiError}</span></div><button onClick={ai?.configuration?.enabled?generateAi:()=>loadAi()} disabled={aiGenerating}>{aiGenerating?<RefreshCw/>:null}{aiGenerating?'Reiniciando…':'Gerar novamente'}</button></div>:!ai?.configuration?.enabled?<div className="ai-analysis-empty"><Settings/><div><b>Configure a inteligência artificial</b><span>Escolha OpenAI ou Claude e cadastre a chave da API para habilitar a análise estratégica.</span></div><button onClick={()=>navigate('/settings')}>Abrir configurações <ArrowRight/></button></div>:!ai.analysis?<div className="ai-analysis-empty"><BrainCircuit/><div><b>Pronto para analisar o perfil base</b><span>A IA usará as métricas e publicações já coletadas. A geração pode levar até 3 minutos e consumir créditos do provedor.</span></div><button onClick={generateAi} disabled={aiGenerating}>{aiGenerating?<RefreshCw/>:<Sparkles/>}{aiGenerating?'Iniciando…':'Gerar primeira análise'}</button></div>:<div className="ai-analysis-content">
        <div className="ai-summary"><div className="ai-score"><strong>{ai.analysis.overallScore}</strong><span>/100</span></div><div><span>RESUMO EXECUTIVO</span><p>{ai.analysis.executiveSummary}</p></div><button onClick={generateAi} disabled={aiGenerating}>{aiGenerating?<RefreshCw/>:<Sparkles/>}{aiGenerating?'Analisando…':'Gerar nova análise'}</button></div>
        <div className="ai-diagnosis">{(ai.analysis.diagnosis||[]).map((item:Row)=><article key={item.area}><div><span>{({performance:'Performance',interaction:'Interação',followers:'Seguidores',sales:'Vendas'} as Row)[item.area]||item.area}</span><strong>{item.score}/100</strong></div><progress max="100" value={item.score}/><p>{item.finding}</p><small>{item.evidence}</small></article>)}</div>
        <div className="ai-analysis-columns"><div><h3>Prioridades recomendadas</h3><div className="ai-priorities">{(ai.analysis.priorities||[]).map((item:Row,index:number)=><article key={`${item.title}-${index}`}><span className={item.priority}>{item.priority==='high'?'Alta':item.priority==='medium'?'Média':'Baixa'}</span><div><h4>{item.title}</h4><p>{item.action}</p><small>{item.expectedImpact} · {item.timeframe}</small></div></article>)}</div></div><div><h3>Ideias de conteúdo</h3><div className="ai-content-ideas">{(ai.analysis.contentIdeas||[]).map((item:Row,index:number)=><article key={`${item.title}-${index}`}><span>{item.format}</span><h4>{item.title}</h4><p><b>Gancho:</b> {item.hook}</p><small>CTA: {item.callToAction}</small></article>)}</div></div></div>
        {!!ai.analysis.competitiveInsights?.length&&<div className="ai-competitive"><h3><Users/> O que aprender com os perfis de comparação</h3><div>{ai.analysis.competitiveInsights.map((item:Row,index:number)=><article key={`${item.competitor}-${index}`}><span>@{String(item.competitor).replace(/^@/,'')}</span><h4>{item.whatWorks}</h4><p>{item.evidence}</p><small><b>Como adaptar:</b> {item.adaptation}</small></article>)}</div></div>}
        {!!ai.analysis.publishingPlan?.length&&<div className="ai-calendar"><h3><CalendarDays/> Plano semanal de publicações</h3><div className="ai-calendar-grid">{ai.analysis.publishingPlan.map((item:Row,index:number)=><article key={`${item.day}-${item.time}-${index}`}><div><b>{item.day}</b><span>{item.time}</span></div><strong>{item.format} · {item.theme}</strong><p>{item.objective}</p><small>CTA: {item.callToAction}</small><em>{item.rationale}</em></article>)}</div></div>}
        {(ai.analysis.hashtagStrategy||ai.analysis.paidMediaPlan)&&<div className="ai-specialist-grid">{ai.analysis.hashtagStrategy&&<article className="ai-hashtags"><h3><Hash/> Estratégia de hashtags</h3><p>{ai.analysis.hashtagStrategy.guidance}</p><b>Recomendadas</b><div>{(ai.analysis.hashtagStrategy.recommended||[]).map((tag:string)=><span key={tag}>{tag.startsWith('#')?tag:`#${tag}`}</span>)}</div><b>Testes</b><div>{(ai.analysis.hashtagStrategy.experiments||[]).map((tag:string)=><span className="test" key={tag}>{tag.startsWith('#')?tag:`#${tag}`}</span>)}</div>{!!ai.analysis.hashtagStrategy.avoid?.length&&<small>Evitar uso indiscriminado: {ai.analysis.hashtagStrategy.avoid.join(', ')}</small>}</article>}{ai.analysis.paidMediaPlan&&<article className="ai-paid-media"><h3><Megaphone/> Plano inicial de mídia paga</h3><dl><div><dt>Objetivo</dt><dd>{ai.analysis.paidMediaPlan.objective}</dd></div><div><dt>Públicos</dt><dd>{(ai.analysis.paidMediaPlan.audiences||[]).join(' · ')}</dd></div><div><dt>Criativo</dt><dd>{ai.analysis.paidMediaPlan.creative}</dd></div><div><dt>Conversão</dt><dd>{ai.analysis.paidMediaPlan.conversionPath}</dd></div><div><dt>Métrica principal</dt><dd>{ai.analysis.paidMediaPlan.primaryMetric}</dd></div><div><dt>Teste</dt><dd>{ai.analysis.paidMediaPlan.testPlan}</dd></div></dl><small>{ai.analysis.paidMediaPlan.caveat}</small></article>}</div>}
        <div className="ai-funnel"><h3>Funil sugerido para vendas</h3><div><article><span>1</span><b>Atração</b><p>{ai.analysis.salesFunnel?.awareness}</p></article><ArrowRight/><article><span>2</span><b>Consideração</b><p>{ai.analysis.salesFunnel?.consideration}</p></article><ArrowRight/><article><span>3</span><b>Conversão</b><p>{ai.analysis.salesFunnel?.conversion}</p></article></div><small>Recomendações de vendas são hipóteses estratégicas quando não há dados de receita ou conversão conectados.</small></div>
      </div>}
    </section>
  </div>
}
